(function(){
  const API='https://security-instructor.onrender.com',K='securityInstructorAdminToken';
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const auth=()=>({Authorization:'Bearer '+(localStorage.getItem(K)||'')});
  async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...auth(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Request failed');return d}
  function addTab(id,label){let b=document.querySelector(`[data-tab="${id}"]`);if(b)return b;const tabs=document.querySelector('.tabs');if(!tabs)return null;b=document.createElement('button');b.className='tab';b.dataset.tab=id;b.textContent=label;tabs.appendChild(b);return b}
  function addPane(id,html){let p=document.getElementById(id);if(p)return p;const host=document.querySelector('.tabs')?.parentElement;if(!host)return null;p=document.createElement('div');p.id=id;p.className='tabpane hidden';p.innerHTML=html;host.appendChild(p);return p}
  function bindTabs(){document.querySelectorAll('.tab').forEach(b=>{if(b.dataset.centerBound)return;b.dataset.centerBound='1';b.addEventListener('click',async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabpane').forEach(x=>x.classList.add('hidden'));b.classList.add('active');const p=document.getElementById(b.dataset.tab);if(p)p.classList.remove('hidden');try{if(b.dataset.tab==='article-moderation')await loadArticles();if(b.dataset.tab==='center-content')await loadContent();if(b.dataset.tab==='center-activity')await loadActivity()}catch(e){alert(e.message)}})});}
  let articles=[];
  function articleRow(x){const ready=x.translationStatus==='ready';let actions=`<button class="btn alt" data-edit="${esc(x.id)}">Edit / تعديل</button> <button class="btn alt" data-preview="${esc(x.id)}">Preview</button>`;if(x.status!=='approved'&&x.status!=='archived')actions+=` <button class="btn" data-approve="${esc(x.id)}">Approve</button>`;if(x.status!=='archived')actions+=` <button class="btn alt" data-archive="${esc(x.id)}">Remove</button>`;return `<tr><td><b>${esc(x.titleAr||'—')}</b><br><span class="muted">${esc(x.titleEn||'—')}</span></td><td>${esc(x.authorName||'—')}<br><span class="muted">${esc(x.authorTitle||'')}</span></td><td>${esc(x.category||'—')}</td><td>${ready?'<span class="status confirmed">Ready / مكتملة</span>':'<span class="status">Pending / ناقصة</span>'}</td><td><span class="status ${esc(x.status)}">${esc(x.status)}</span></td><td>${x.wordCountEn||0}/${x.wordCountAr||0}</td><td>${actions}</td></tr>`}
  async function loadArticles(){const el=document.getElementById('centerArticlesRows');if(!el)return;try{articles=await api('/api/admin/articles');el.innerHTML=articles.length?articles.map(articleRow).join(''):'<tr><td colspan="7">No articles / لا توجد مقالات</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>preview(b.dataset.preview));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve));document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archive(b.dataset.archive))}catch(e){el.innerHTML='<tr><td colspan="7">'+esc(e.message)+'</td></tr>'}}
  async function approve(id){try{await api('/api/admin/articles/'+encodeURIComponent(id)+'/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'approved'})});await log('approve_article',id,'Article approved from Admin Dashboard');await loadArticles()}catch(e){alert(e.message)}}
  async function archive(id){if(!confirm('Remove this article from the public website? / هل تريد إزالة المقال من الموقع؟'))return;try{await api('/api/admin/articles/'+encodeURIComponent(id)+'/archive',{method:'PATCH'});await log('archive_article',id,'Article archived from Admin Dashboard');await loadArticles()}catch(e){alert(e.message)}}
  function preview(id){const x=articles.find(a=>a.id===id);if(!x)return;const w=window.open('','_blank');w.document.write('<html dir="rtl"><body style="font-family:Arial;max-width:1100px;margin:35px;line-height:1.9"><h1>'+esc(x.titleAr||'')+'</h1><h2>'+esc(x.titleEn||'')+'</h2><p><b>'+esc(x.authorName||'')+'</b> — '+esc(x.authorTitle||'')+'</p><hr><h3>العربية</h3><p>'+esc(x.contentAr||'').replace(/\r?\n/g,'<br><br>')+'</p><hr><h3>English</h3><p>'+esc(x.contentEn||'').replace(/\r?\n/g,'<br><br>')+'</p></body></html>');w.document.close()}
  function ensureModal(){if(document.getElementById('centerEditModal'))return;const d=document.createElement('div');d.id='centerEditModal';d.style.cssText='display:none;position:fixed;inset:0;background:rgba(4,15,25,.82);z-index:9999;align-items:center;justify-content:center;padding:18px';d.innerHTML='<div style="width:min(1100px,96vw);max-height:92vh;overflow:auto;background:#102A43;border:1px solid #c8a96b;padding:24px;color:#fff"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">Edit Article / تعديل المقال</h2><button id="centerClose" class="btn alt">Close / إغلاق</button></div><p id="centerEditNote" class="muted"></p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><label>English Title<input id="ceTitleEn" style="width:100%;padding:10px;background:#0B1F33;color:#fff;border:1px solid #526577"></label><label>Arabic Title<input id="ceTitleAr" dir="rtl" style="width:100%;padding:10px;background:#0B1F33;color:#fff;border:1px solid #526577"></label><label>Author<input id="ceAuthor" style="width:100%;padding:10px;background:#0B1F33;color:#fff;border:1px solid #526577"></label><label>Professional Title<input id="ceAuthorTitle" style="width:100%;padding:10px;background:#0B1F33;color:#fff;border:1px solid #526577"></label><label>Category<input id="ceCategory" style="width:100%;padding:10px;background:#0B1F33;color:#fff;border:1px solid #526577"></label><label>Author Image URL<input id="ceImage" style="width:100%;padding:10px;background:#0B1F33;color:#fff;border:1px solid #526577"></label><label style="grid-column:1/-1">English Summary<textarea id="ceExcerptEn" style="width:100%;min-height:100px;background:#0B1F33;color:#fff;border:1px solid #526577"></textarea></label><label style="grid-column:1/-1">Arabic Summary<textarea id="ceExcerptAr" dir="rtl" style="width:100%;min-height:100px;background:#0B1F33;color:#fff;border:1px solid #526577"></textarea></label><label style="grid-column:1/-1">English Article<textarea id="ceContentEn" style="width:100%;min-height:240px;background:#0B1F33;color:#fff;border:1px solid #526577"></textarea></label><label style="grid-column:1/-1">Arabic Article<textarea id="ceContentAr" dir="rtl" style="width:100%;min-height:240px;background:#0B1F33;color:#fff;border:1px solid #526577"></textarea></label></div><button id="centerSave" class="btn" style="margin-top:14px">Save Changes / حفظ التعديلات</button><div id="centerEditStatus" class="muted" style="margin-top:10px"></div></div>';document.body.appendChild(d);centerClose.onclick=()=>d.style.display='none';}
  function openEdit(id){ensureModal();const x=articles.find(a=>a.id===id);if(!x)return;ceTitleEn.value=x.titleEn||'';ceTitleAr.value=x.titleAr||'';ceAuthor.value=x.authorName||'';ceAuthorTitle.value=x.authorTitle||'';ceCategory.value=x.category||'';ceImage.value=x.authorImage||'';ceExcerptEn.value=x.excerptEn||'';ceExcerptAr.value=x.excerptAr||'';ceContentEn.value=x.contentEn||'';ceContentAr.value=x.contentAr||'';centerEditNote.textContent='Translation: '+(x.translationStatus==='ready'?'Ready / مكتملة':'Pending / ناقصة');centerEditStatus.textContent='';centerEditModal.style.display='flex';centerSave.onclick=async()=>{centerEditStatus.textContent='Saving…';try{await api('/api/admin/articles/'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({titleEn:ceTitleEn.value,titleAr:ceTitleAr.value,authorName:ceAuthor.value,authorTitle:ceAuthorTitle.value,category:ceCategory.value,authorImage:ceImage.value,excerptEn:ceExcerptEn.value,excerptAr:ceExcerptAr.value,contentEn:ceContentEn.value,contentAr:ceContentAr.value})});await log('edit_article',id,'Article updated from Admin Dashboard');centerEditStatus.textContent='Saved / تم الحفظ';setTimeout(()=>{centerEditModal.style.display='none';loadArticles()},500)}catch(e){centerEditStatus.textContent=e.message}};}
  async function loadContent(){const rows=document.getElementById('contentRows');if(!rows)return;try{const d=await api('/api/admin/site-content');rows.innerHTML=d.map(x=>`<tr><td>${esc(x.key)}</td><td><input data-en="${esc(x.key)}" value="${esc(x.en||'')}" style="min-width:260px;background:#0B1F33;color:#fff;border:1px solid #526577;padding:8px"></td><td><input data-ar="${esc(x.key)}" dir="rtl" value="${esc(x.ar||'')}" style="min-width:260px;background:#0B1F33;color:#fff;border:1px solid #526577;padding:8px"></td><td><button class="btn" data-content-save="${esc(x.key)}">Save / حفظ</button></td></tr>`).join('')||'<tr><td colspan="4">No content entries yet / لا توجد عناصر محتوى</td></tr>';document.querySelectorAll('[data-content-save]').forEach(b=>b.onclick=async()=>{const key=b.dataset.contentSave,en=document.querySelector(`[data-en="${CSS.escape(key)}"]`).value,ar=document.querySelector(`[data-ar="${CSS.escape(key)}"]`).value;try{await api('/api/admin/site-content',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,en,ar})});await log('edit_site_content',key,'Site content updated from Admin Dashboard');alert('Saved / تم الحفظ')}catch(e){alert(e.message)}})}catch(e){rows.innerHTML='<tr><td colspan="4">'+esc(e.message)+'</td></tr>'}}
  async function loadActivity(){const rows=document.getElementById('activityRows');if(!rows)return;try{const d=await api('/api/admin/activity');rows.innerHTML=d.length?d.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString()}</td><td>${esc(x.action)}</td><td>${esc(x.targetId||'')}</td><td>${esc(x.details||'')}</td></tr>`).join(''):'<tr><td colspan="4">No activity yet / لا توجد تغييرات مسجلة</td></tr>'}catch(e){rows.innerHTML='<tr><td colspan="4">'+esc(e.message)+'</td></tr>'}}
  async function log(action,targetId,details){try{await api('/api/admin/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,targetId,details})})}catch{}}
  function boot(){if(!document.querySelector('#dashboard')||!document.querySelector('.tabs'))return;addTab('article-moderation','Articles / المقالات');addPane('article-moderation','<div class="toolbar"><button class="btn alt" id="centerArticleRefresh">Refresh / تحديث</button></div><div class="table-wrap"><table><thead><tr><th>المقال</th><th>الكاتب</th><th>التصنيف</th><th>الترجمة</th><th>الحالة</th><th>الكلمات</th><th>إجراء</th></tr></thead><tbody id="centerArticlesRows"></tbody></table></div>');addTab('center-content','Content Management / إدارة المحتوى');addPane('center-content','<div class="notice">تحرير النصوص العامة المربوطة بالموقع دون تعديل الكود أو الإعدادات الأمنية.</div><div class="table-wrap"><table><thead><tr><th>Key</th><th>English</th><th>العربية</th><th>إجراء</th></tr></thead><tbody id="contentRows"></tbody></table></div>');addTab('center-activity','Activity Log / سجل التغييرات');addPane('center-activity','<div class="toolbar"><button class="btn alt" id="activityRefresh">Refresh / تحديث</button></div><div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>Action</th><th>Target</th><th>Details</th></tr></thead><tbody id="activityRows"></tbody></table></div>');bindTabs();document.getElementById('centerArticleRefresh').onclick=loadArticles;document.getElementById('activityRefresh').onclick=loadActivity;setTimeout(loadArticles,0)}
  window.addEventListener('DOMContentLoaded',boot);
})();
(function(){var s=document.createElement('script');s.src='reports-center.js?v=20260915';document.head.appendChild(s);})();
