(function(){
  const API='https://security-instructor.onrender.com',K='securityInstructorAdminToken';
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const auth=()=>({Authorization:'Bearer '+(localStorage.getItem(K)||'')});
  async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...auth(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||('Request failed ('+r.status+')'));return d}
  function add(){
    const tabs=document.querySelector('.tabs');if(!tabs||document.querySelector('[data-tab="training-certificates"]'))return false;
    const b=document.createElement('button');b.className='tab';b.dataset.tab='training-certificates';b.textContent='شهادات التدريب / Certificates';tabs.appendChild(b);
    const host=tabs.parentElement,p=document.createElement('div');p.id='training-certificates';p.className='tabpane hidden';p.innerHTML=`<div class="toolbar"><input id="certSearch" placeholder="بحث برقم الشهادة أو المتدرب أو الدورة"><select id="certFilter"><option value="">كل الحالات</option><option value="valid">Valid</option><option value="revoked">Revoked</option></select><button class="btn alt" id="certRefresh">تحديث</button></div><div class="notice" style="margin:0 0 14px;padding:12px;background:#0B1F33;border:1px solid var(--line);color:var(--muted);line-height:1.7">الشهادة تُنشأ تلقائيًا عند تحويل التسجيل إلى <b style="color:#c8a96b">completed</b>. ويمكن إصدارها يدويًا من هنا لأي تسجيل مكتمل.</div><div class="table-wrap"><table><thead><tr><th>Certificate ID</th><th>المتدرب</th><th>Trainee ID</th><th>الدورة</th><th>تاريخ الإصدار</th><th>Email</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody id="certificateRows"></tbody></table></div>`;host.appendChild(p);
    b.addEventListener('click',async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabpane').forEach(x=>x.classList.add('hidden'));b.classList.add('active');p.classList.remove('hidden');await load()});
    document.getElementById('certRefresh').onclick=load;document.getElementById('certSearch').oninput=load;document.getElementById('certFilter').onchange=load;
    return true;
  }
  async function load(){const rows=document.getElementById('certificateRows');if(!rows)return;rows.innerHTML='<tr><td colspan="8">Loading…</td></tr>';try{let d;try{d=await api('/api/admin/certificates/list')}catch(e){if(!String(e.message||'').includes('404'))throw e;try{d=await api('/api/admin/certificates')}catch(e2){if(!String(e2.message||'').includes('404'))throw e2;d=await api('/api/admin/training-certificates')}}let a=d.certificates||[];if(!a.length){try{await api('/api/admin/certificates/repair',{method:'POST'});const retry=await api('/api/admin/certificates/list');a=retry.certificates||[]}catch(repairErr){console.warn('Certificate repair:',repairErr)}}const q=(document.getElementById('certSearch').value||'').toLowerCase(),f=document.getElementById('certFilter').value||'';if(q)a=a.filter(x=>[x.certificateId,x.traineeId,x.recipientNameEn,x.recipientNameAr,x.courseNameEn,x.courseNameAr,x.email].some(v=>String(v||'').toLowerCase().includes(q)));if(f)a=a.filter(x=>x.verificationStatus===f);rows.innerHTML=a.length?a.map(x=>{const issued=x.issuedAt?new Date(x.issuedAt).toLocaleString():'—';return `<tr><td class="ltr"><b>${esc(x.certificateId)}</b></td><td><b>${esc(x.recipientNameAr||'—')}</b><br><span class="muted">${esc(x.recipientNameEn||'—')}</span></td><td class="ltr">${esc(x.traineeId)}</td><td>${esc(x.courseNameAr||'—')}<br><span class="muted">${esc(x.courseNameEn||'—')}</span></td><td>${esc(issued)}</td><td class="ltr">${esc(x.email||'—')}<br><span class="muted">${esc(x.emailStatus||'—')}</span></td><td><span class="status ${x.verificationStatus==='valid'?'completed':'cancelled'}">${esc(x.verificationStatus||'—')}</span></td><td><button class="btn alt" data-view-cert="${esc(x.certificateId)}">عرض الشهادة</button> <button class="btn alt" data-verify-cert="${esc(x.certificateId)}">التحقق</button></td></tr>`}).join(''):'<tr><td colspan="8">لا توجد شهادات / No certificates</td></tr>';document.querySelectorAll('[data-view-cert]').forEach(b=>b.onclick=()=>window.open('certificate.html?id='+encodeURIComponent(b.dataset.viewCert),'_blank'));document.querySelectorAll('[data-verify-cert]').forEach(b=>b.onclick=()=>window.open('verify.html?type=certificate&id='+encodeURIComponent(b.dataset.verifyCert),'_blank'))}catch(e){rows.innerHTML='<tr><td colspan="8">'+esc(e.message)+'</td></tr>'}}
  function boot(){if(!document.querySelector('#dashboard')||!document.querySelector('.tabs'))return;add()}
  if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot);else boot();
  window.SICertificates={refresh:load};
})();
