// Deployed statistics API
window.APP_CONFIG={API_BASE:'https://security-instructor.onrender.com'};
window.addEventListener('DOMContentLoaded',function(){
var isHome=location.pathname.endsWith('/index.html')||location.pathname.endsWith('/');
var isLegacyChallenge=location.pathname.endsWith('/challenge.html');
if(isLegacyChallenge){location.replace('challenge-free.html');return;}
var challengeDone=localStorage.getItem('securityKnowledgeChallengeCompleted')==='true';
if(isHome&&!challengeDone){location.replace('challenge-free.html');return;}
var nav=document.querySelector('.topbar nav');
if(nav&&!nav.querySelector('a[href="challenge-free.html"]')){var link=document.createElement('a');link.href='challenge-free.html';link.innerHTML='Challenge / التحدي';link.setAttribute('aria-label','Security Knowledge Challenge / اختبر معلوماتك الأمنية');var courses=nav.querySelector('a[href="#courses"]');if(courses&&courses.nextSibling)nav.insertBefore(link,courses.nextSibling);else nav.appendChild(link);}
document.addEventListener('click',function(e){var button=e.target.closest('[data-course]');if(!button)return;var slug=button.getAttribute('data-course');if(!slug)return;e.preventDefault();e.stopImmediatePropagation();location.href='course-details.html?course='+encodeURIComponent(slug);},true);
var slugs=['traffic-management-vehicle-control','crowd-management-event-security','fire-safety-emergency-response','vehicle-search-security-inspection','person-search-security-screening'];
slugs.forEach(function(slug){var trigger=document.querySelector('[data-course="'+slug+'"]');if(!trigger||document.querySelector('[data-course-assessment="'+slug+'"]'))return;var a=document.createElement('a');a.setAttribute('data-course-assessment',slug);a.href='course-assessment-v2.html?course='+encodeURIComponent(slug);a.innerHTML='Initial Course Assessment / التقييم المبدئي للدورة';a.style.cssText='display:inline-block;margin:10px 8px 0 0;padding:11px 16px;border:1px solid #c8a96b;color:#c8a96b;background:transparent;text-decoration:none;font-weight:800;';trigger.insertAdjacentElement('afterend',a);});
var hero=document.getElementById('home');
if(hero&&!document.getElementById('securityChallengePromo')){var section=document.createElement('section');section.id='securityChallengePromo';section.style.cssText='margin:0;padding:34px 7%;background:linear-gradient(135deg,#102A43,#0B1F33);border-top:1px solid #294158;border-bottom:1px solid #294158;';section.innerHTML='<div style="max-width:1180px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:28px;flex-wrap:wrap"><div style="flex:1;min-width:280px"><div style="font-size:13px;letter-spacing:.12em;font-weight:700;color:#c8a96b;margin-bottom:8px">SECURITY AWARENESS • PRACTICAL SITUATIONS</div><h2 style="margin:0 0 8px;font-size:clamp(24px,3vw,38px);color:#fff">🛡️ SECURITY KNOWLEDGE CHALLENGE</h2><div style="font-size:22px;font-weight:700;color:#dbe2e8;margin-bottom:10px;direction:rtl;text-align:left">اختبر معلوماتك الأمنية</div><p style="margin:0;color:#cbd5df;line-height:1.7;max-width:760px">Test your general security awareness with 10 randomly selected questions.<br><span style="direction:rtl;display:inline-block">اختبر معلوماتك الأمنية العامة من خلال أسئلة عشوائية.</span></p></div><div style="flex:0 0 auto"><a href="challenge-free.html" style="display:inline-block;background:#c8a96b;color:#101820;text-decoration:none;font-weight:800;padding:15px 24px;border:1px solid #c8a96b">Start Challenge / ابدأ التحدي</a></div></div>';hero.insertAdjacentElement('afterend',section);}
var contact=document.getElementById('contact');
if(contact&&!document.getElementById('ownerContactDetails')){var box=document.createElement('div');box.id='ownerContactDetails';box.style.cssText='margin-top:28px;padding:22px 24px;background:#102A43;border:1px solid #294158;border-left:3px solid #c8a96b;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;';box.innerHTML='<div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Egypt Phone 1 / رقم مصر 1</strong><a href="tel:+201555424683" style="color:#fff;text-decoration:none">+20 15 55424683</a></div><div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Egypt Phone 2 / رقم مصر 2</strong><a href="tel:+201100286646" style="color:#fff;text-decoration:none">+20 11 00286646</a></div><div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Alternate Outlook Email / بريد Outlook البديل</strong><a href="mailto:Abdallah-Shalaby1@outlook.com" style="color:#fff;text-decoration:none;overflow-wrap:anywhere">Abdallah-Shalaby1@outlook.com</a></div>';contact.appendChild(box);}
if(contact&&!document.getElementById('ownerSocialLinks')){var social=document.createElement('div');social.id='ownerSocialLinks';social.style.cssText='margin-top:18px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;';social.innerHTML='<span style="color:#c8a96b;font-weight:800;margin-right:6px">Social / التواصل</span><a href="https://www.linkedin.com/in/abdallah-abdelaziz-bba-cpo-assd-psfrd-tot-ssmp-9a8485183/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" title="LinkedIn" style="width:40px;height:40px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #c8a96b;color:#fff;text-decoration:none;font-weight:900;border-radius:50%">in</a><a href="https://www.instagram.com/abdallah.abdelaziz?stkn=MTg5MWVtMXVnYmdnag%3D%3D&utm_source=qr" target="_blank" rel="noopener noreferrer" aria-label="Instagram" title="Instagram" style="width:40px;height:40px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #c8a96b;color:#fff;text-decoration:none;font-weight:900;border-radius:50%">◎</a><a href="https://www.tiktok.com/@abdallah.abdelaziz0?_r=1&_t=ZS-99c5D0EVTSm" target="_blank" rel="noopener noreferrer" aria-label="TikTok" title="TikTok" style="width:40px;height:40px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #c8a96b;color:#fff;text-decoration:none;font-weight:900;border-radius:50%">♪</a>';contact.appendChild(social);}
setTimeout(function(){var adminCourseBtn=document.getElementById('adminCourseBtn');if(adminCourseBtn){adminCourseBtn.dataset.en='Available Courses';adminCourseBtn.dataset.ar='الدورات المتاحة';adminCourseBtn.textContent='Available Courses';}['vehicle-search-security-inspection','person-search-security-screening'].forEach(function(slug){var card=document.querySelector('[data-course="'+slug+'"]');if(!card)return;var article=card.closest('.course-card');if(article){var badge=article.querySelector('.course-card-media span');if(badge)badge.textContent='Available / متاحة';card.textContent='View Course / عرض الدورة';}});},0);
});