// Deployed statistics API
window.APP_CONFIG={API_BASE:'https://security-instructor.onrender.com'};
window.addEventListener('DOMContentLoaded',function(){
var isHome=location.pathname.endsWith('/index.html')||location.pathname.endsWith('/');
var isLegacyChallenge=location.pathname.endsWith('/challenge.html');
if(isLegacyChallenge){location.replace('challenge-free.html');return;}
var challengeDone=localStorage.getItem('securityKnowledgeChallengeCompleted')==='true';
if(isHome&&!challengeDone){location.replace('challenge-free.html');return;}
var nav=document.querySelector('.topbar nav');
if(nav&&!nav.querySelector('a[href="challenge-free.html"]')){var link=document.createElement('a');link.href='challenge-free.html';link.innerHTML='Challenge / التحدي';link.setAttribute('aria-label','Security Knowledge Challenge / اختبر معلوماتك الأمنية');var courses=nav.querySelector('a[href="#courses"]');if(courses&&courses.nextSibling)nav.insertBefore(link,courses.nextSibling);else nav.appendChild(link);}
document.addEventListener('click',function(e){var button=e.target.closest('[data-course]');if(!button)return;var slug=button.getAttribute('data-course');if(!slug)return;e.preventDefault();e.stopImmediatePropagation();location.href='course-details.html?course='+encodeURIComponent(slug);},true);
var slugs=['traffic-management-vehicle-control','crowd-management-event-security','fire-safety-emergency-response','vehicle-search-security-inspection','person-search-security-screening'];
slugs.forEach(function(slug){var trigger=document.querySelector('[data-course="'+slug+'"]');if(!trigger||document.querySelector('[data-course-assessment="'+slug+'"]'))return;var a=document.createElement('a');a.setAttribute('data-course-assessment',slug);a.href='course-assessment-v2.html?course='+encodeURIComponent(slug);a.innerHTML='Initial Course Assessment / التقييم المبدئي للدورة';a.style.cssText='display:inline-block;margin:10px 8px 0 0;padding:11px 16px;border:1px solid #c8a96b;color:#c8a96b;background:transparent;text-decoration:none;font-weight:800;';trigger.insertAdjacentElement('afterend',a);});
var hero=document.getElementById('home');
if(hero&&!document.getElementById('securityChallengePromo')){var section=document.createElement('section');section.id='securityChallengePromo';section.style.cssText='margin:0;padding:34px 7%;background:linear-gradient(135deg,#102A43,#0B1F33);border-top:1px solid #294158;border-bottom:1px solid #294158;';section.innerHTML='<div style="max-width:1180px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:28px;flex-wrap:wrap"><div style="flex:1;min-width:280px"><div style="font-size:13px;letter-spacing:.12em;font-weight:700;color:#c8a96b;margin-bottom:8px">SECURITY AWARENESS • PRACTICAL SITUATIONS</div><h2 style="margin:0 0 8px;font-size:clamp(24px,3vw,38px);color:#fff">🛡️ SECURITY KNOWLEDGE CHALLENGE</h2><div style="font-size:22px;font-weight:700;color:#dbe2e8;margin-bottom:10px;direction:rtl;text-align:left">اختبر معلوماتك الأمنية</div><p style="margin:0;color:#cbd5df;line-height:1.7;max-width:760px">Test your general security awareness with 10 randomly selected questions.<br><span style="direction:rtl;display:inline-block">اختبر معلوماتك الأمنية العامة من خلال أسئلة عشوائية.</span></p></div><div style="flex:0 0 auto"><a href="challenge-free.html" style="display:inline-block;background:#c8a96b;color:#101820;text-decoration:none;font-weight:800;padding:15px 24px;border:1px solid #c8a96b">Start Challenge / ابدأ التحدي</a></div></div>';hero.insertAdjacentElement('afterend',section);}
var contact=document.getElementById('contact');
if(contact&&!document.getElementById('ownerContactDetails')){
var intro=document.createElement('div');intro.id='ownerContactIntro';intro.style.cssText='margin-top:28px;text-align:center;padding:8px 10px 20px;';
intro.innerHTML='<div style="font-size:22px;font-weight:800;color:#fff;margin-bottom:6px">Let’s Connect / يسعدنا تواصلك معنا</div><div style="font-size:15px;line-height:1.8;color:#cbd5df">We look forward to discussing training, collaboration and professional opportunities through the following channels.<br><span style="direction:rtl;display:inline-block">يسعدنا مناقشة فرص التدريب والتعاون والتواصل المهني عبر قنوات الاتصال التالية.</span></div>';
contact.appendChild(intro);
var box=document.createElement('div');box.id='ownerContactDetails';box.style.cssText='margin-top:0;padding:22px 24px;background:#102A43;border:1px solid #294158;border-left:3px solid #c8a96b;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;';
box.innerHTML='<div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Email 1 / البريد الإلكتروني 1</strong><a href="mailto:abdallahabdalaziz@yahoo.com" style="color:#fff;text-decoration:none;overflow-wrap:anywhere">abdallahabdalaziz@yahoo.com</a></div><div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Email 2 / البريد الإلكتروني 2</strong><a href="mailto:Abdallah-Shalaby1@outlook.com" style="color:#fff;text-decoration:none;overflow-wrap:anywhere">Abdallah-Shalaby1@outlook.com</a></div><div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Phone 1 / الهاتف 1</strong><a href="tel:+966506340246" style="color:#fff;text-decoration:none">+966 50 634 0246</a></div><div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Phone 2 / الهاتف 2</strong><a href="tel:+201555424683" style="color:#fff;text-decoration:none">+20 15 55424683</a></div><div><strong style="display:block;color:#c8a96b;margin-bottom:6px">Phone 3 / الهاتف 3</strong><a href="tel:+201100286646" style="color:#fff;text-decoration:none">+20 11 00286646</a></div><div><strong style="display:block;color:#c8a96b;margin-bottom:6px">WhatsApp / واتساب</strong><a href="https://wa.me/201100286646" target="_blank" rel="noopener noreferrer" style="color:#fff;text-decoration:none">+20 11 00286646</a></div>';
contact.appendChild(box);
}
if(contact&&!document.getElementById('ownerSocialLinks')){
var social=document.createElement('div');social.id='ownerSocialLinks';social.style.cssText='margin-top:26px;text-align:center;padding:8px 10px 20px;';
social.innerHTML='<div style="font-size:21px;font-weight:800;color:#fff;margin-bottom:5px">Follow Me on Social Media / تابعوني على منصات التواصل الاجتماعي</div><div style="font-size:14px;color:#cbd5df;line-height:1.7;margin-bottom:16px">We look forward to connecting with you through the following platforms.<br><span style="direction:rtl;display:inline-block">ننتظر تواصلكم معنا ومناقشتنا عبر المنصات التالية.</span></div><div style="display:flex;justify-content:center;align-items:flex-start;gap:22px;flex-wrap:wrap"><a href="https://www.linkedin.com/in/abdallah-abdelaziz-bba-cpo-assd-psfrd-tot-ssmp-9a8485183/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" title="LinkedIn" style="width:58px;height:58px;display:inline-flex;align-items:center;justify-content:center;border:2px solid #0A66C2;color:#fff;text-decoration:none;font-weight:900;font-size:22px;border-radius:50%;background:#0A66C2;box-shadow:0 4px 14px rgba(0,0,0,.22)">in</a><a href="https://www.instagram.com/abdallah.abdelaziz?stkn=MTg5MWVtMXVnYmdnag%3D%3D&utm_source=qr" target="_blank" rel="noopener noreferrer" aria-label="Instagram" title="Instagram" style="width:58px;height:58px;display:inline-flex;align-items:center;justify-content:center;border:2px solid #E1306C;color:#fff;text-decoration:none;font-weight:900;font-size:27px;border-radius:50%;background:linear-gradient(135deg,#833AB4,#E1306C,#F77737,#FCAF45);box-shadow:0 4px 14px rgba(0,0,0,.22)">◎</a><a href="https://www.tiktok.com/@abdallah.abdelaziz0?_r=1&_t=ZS-99c5D0EVTSm" target="_blank" rel="noopener noreferrer" aria-label="TikTok" title="TikTok" style="width:58px;height:58px;display:inline-flex;align-items:center;justify-content:center;border:2px solid #fff;color:#fff;text-decoration:none;font-weight:900;font-size:27px;border-radius:50%;background:#000;box-shadow:0 4px 14px rgba(0,0,0,.22)">♪</a><a href="https://wa.me/201100286646" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp" title="WhatsApp" style="width:58px;height:58px;display:inline-flex;align-items:center;justify-content:center;border:2px solid #25D366;color:#fff;text-decoration:none;font-weight:900;font-size:27px;border-radius:50%;background:#25D366;box-shadow:0 4px 14px rgba(0,0,0,.22)">◔</a></div><div style="margin-top:14px;color:#c8a96b;font-size:13px;font-weight:700">LinkedIn &nbsp; • &nbsp; Instagram &nbsp; • &nbsp; TikTok &nbsp; • &nbsp; WhatsApp</div>';
contact.appendChild(social);
}
setTimeout(function(){var adminCourseBtn=document.getElementById('adminCourseBtn');if(adminCourseBtn){adminCourseBtn.dataset.en='Available Courses';adminCourseBtn.dataset.ar='الدورات المتاحة';adminCourseBtn.textContent='Available Courses';}['vehicle-search-security-inspection','person-search-security-screening'].forEach(function(slug){var card=document.querySelector('[data-course="'+slug+'"]');if(!card)return;var article=card.closest('.course-card');if(article){var badge=article.querySelector('.course-card-media span');if(badge)badge.textContent='Available / متاحة';card.textContent='View Course / عرض الدورة';}});},0);
});