(function(){
  var slug=new URLSearchParams(location.search).get('course');
  if(!slug)return;
  var API=(window.APP_CONFIG&&window.APP_CONFIG.API_BASE)||'';
  var wrap=document.createElement('section');
  wrap.id='courseStats';
  wrap.style.cssText='margin-top:42px;border:1px solid #294158;background:#102A43;padding:24px;';
  wrap.innerHTML='<h2 style="margin:0 0 6px;color:#fff;font-size:28px">Course Statistics <small style="display:block;color:#dbe2e8;font-size:21px;direction:rtl;text-align:right;font-family:Tahoma,Arial">إحصائيات الدورة</small></h2><p style="color:#cbd5df;margin:0 0 20px">Live course activity and learner ratings / نشاط الدورة وتقييمات المتدربين</p><div id="statsGrid" style="display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px"></div><div id="ratingBox" style="margin-top:20px;border-top:1px solid #294158;padding-top:20px"><strong style="color:#c8a96b">Rate this course / قيّم هذه الدورة</strong><div id="stars" style="margin-top:12px;display:flex;gap:7px;flex-wrap:wrap"></div><div id="ratingMsg" style="margin-top:10px;color:#cbd5df;font-size:14px"></div></div>';
  var target=document.querySelector('.footer-actions')||document.querySelector('main');
  if(target)target.insertAdjacentElement('afterend',wrap); else document.body.appendChild(wrap);
  var labels=[['Views','المشاهدات','views'],['Course Entries','مرات الدخول','entries'],['Positive Ratings','التقييمات الإيجابية','positiveRatings'],['Average Rating','متوسط التقييم','averageRating'],['Rating Count','عدد التقييمات','ratingCount']];
  var grid=wrap.querySelector('#statsGrid');labels.forEach(function(x){var d=document.createElement('div');d.style.cssText='background:#0d2439;border:1px solid #294158;padding:17px;text-align:center';d.innerHTML='<div style="font-size:12px;color:#c8a96b;font-weight:800">'+x[0]+'</div><div style="font-size:22px;font-weight:900;color:#fff;margin:5px 0">—</div><div style="font-size:13px;color:#cbd5df;direction:rtl">'+x[1]+'</div>';d.dataset.key=x[2];grid.appendChild(d)});
  function setStats(s){labels.forEach(function(x){var d=grid.querySelector('[data-key="'+x[2]+'"]');if(!d)return;var v=s[x[2]];if(x[2]==='averageRating'&&typeof v==='number')v=v.toFixed(1);d.children[1].textContent=(v===undefined||v===null)?'—':v;});}
  function load(){if(!API)return;fetch(API.replace(/\/$/,'')+'/api/course-stats/'+encodeURIComponent(slug)).then(function(r){if(!r.ok)throw new Error();return r.json()}).then(setStats).catch(function(){})}
  function entry(){if(!API)return;fetch(API.replace(/\/$/,'')+'/api/course-stats/'+encodeURIComponent(slug)+'/entry',{method:'POST',headers:{'Content-Type':'application/json'}}).then(function(r){if(!r.ok)throw new Error();return r.json()}).then(setStats).catch(function(){})}
  var stars=wrap.querySelector('#stars');for(var i=1;i<=5;i++){(function(n){var b=document.createElement('button');b.type='button';b.textContent='★ '+n;b.style.cssText='border:1px solid #c8a96b;background:transparent;color:#c8a96b;padding:9px 13px;cursor:pointer;font-weight:800';b.onclick=function(){if(!API){wrap.querySelector('#ratingMsg').textContent='Ratings will be enabled when the statistics service is connected. / سيتم تفعيل التقييمات بعد ربط خدمة الإحصائيات.';return}fetch(API.replace(/\/$/,'')+'/api/course-stats/'+encodeURIComponent(slug)+'/rating',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating:n})}).then(function(r){if(!r.ok)throw new Error();return r.json()}).then(function(s){setStats(s);wrap.querySelector('#ratingMsg').textContent='Thank you for your rating. / شكرًا لتقييمك.'}).catch(function(){wrap.querySelector('#ratingMsg').textContent='Unable to save the rating right now. / تعذر حفظ التقييم حاليًا.'})};stars.appendChild(b)})(i)}
  load();entry();
})();
