(function(){
  const API='https://security-instructor.onrender.com',K='securityInstructorAdminToken';
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const auth=()=>({Authorization:'Bearer '+(localStorage.getItem(K)||'')});
  async function loadScript(src,readyCheck){if(readyCheck())return true;return new Promise(resolve=>{const s=document.createElement('script');s.src=src;s.onload=()=>resolve(!!readyCheck());s.onerror=()=>resolve(false);document.head.appendChild(s)})}
  function addTab(){if(document.querySelector('[data-tab="reports-center"]'))return;const tabs=document.querySelector('.tabs');if(!tabs)return;const b=document.createElement('button');b.className='tab';b.dataset.tab='reports-center';b.textContent='Reports Center';tabs.appendChild(b);b.addEventListener('click',activate)}
  function addPane(){if(document.getElementById('reports-center'))return;const host=document.querySelector('.tabs')?.parentElement;if(!host)return;const p=document.createElement('div');p.id='reports-center';p.className='tabpane hidden';p.innerHTML=`<div style="padding:4px 0 18px"><div class="eyebrow">REPORTING & ANALYTICS</div><h2 style="margin:7px 0 4px">Reports Center</h2><div class="muted">All report outputs are generated in English. Export to Excel, Word, or PDF/Print.</div></div><div class="report-toolbar" style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px"><label>Report Type<select id="reportType" style="width:100%;padding:11px;background:#0B1F33;border:1px solid #526577;color:#fff"><option value="courses">Training Courses Report</option><option value="trainees">Trainee Master Report</option><option value="feedback">Feedback Report</option><option value="assessments">Assessment Results Report</option><option value="complaints">Trainee Complaints Report</option><option value="challenge">Challenge Results Report</option></select></label><label>From<input id="reportFrom" type="date" style="width:100%;padding:11px;background:#0B1F33;border:1px solid #526577;color:#fff"></label><label>To<input id="reportTo" type="date" style="width:100%;padding:11px;background:#0B1F33;border:1px solid #526577;color:#fff"></label><label>Course<select id="reportCourse" style="width:100%;padding:11px;background:#0B1F33;border:1px solid #526577;color:#fff"><option value="">All Courses</option></select></label></div><div class="toolbar"><button class="btn" id="generateReport">Generate Report</button><button class="btn alt" id="exportExcel" disabled>Export Excel</button><button class="btn alt" id="exportWord" disabled>Export Word</button><button class="btn alt" id="exportPdf" disabled>Print / PDF</button></div><div id="reportSummary" class="challenge-state" style="margin-bottom:14px">No report generated yet.</div><div class="table-wrap"><table id="reportTable"><thead></thead><tbody><tr><td>No report generated yet.</td></tr></tbody></table></div><div class="note">Assessment and complaint reports will populate automatically when corresponding records exist in the database. No placeholder data is created.</div>`;host.appendChild(p);}
  let current={title:'',columns:[],rows:[],summary:{}};
  async function loadCourses(){try{const rows=await fetch(API+'/api/courses').then(r=>r.json());const s=document.getElementById('reportCourse');if(s)s.innerHTML='<option value="">All Courses</option>'+rows.map(x=>`<option value="${esc(x.slug)}">${esc(x.en)}</option>`).join('')}catch{}}
  function activate(){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabpane').forEach(x=>x.classList.add('hidden'));const b=document.querySelector('[data-tab="reports-center"]');b?.classList.add('active');document.getElementById('reports-center')?.classList.remove('hidden')}
  function render(){const th=document.querySelector('#reportTable thead'),tb=document.querySelector('#reportTable tbody');th.innerHTML='<tr>'+current.columns.map(c=>'<th>'+esc(c)+'</th>').join('')+'</tr>';tb.innerHTML=current.rows.length?current.rows.map(r=>'<tr>'+current.columns.map(c=>'<td>'+esc(r[c])+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+Math.max(current.columns.length,1)+'">No data found for the selected filters.</td></tr>';const s=current.summary||{};document.getElementById('reportSummary').innerHTML='<strong>'+esc(current.title)+'</strong><br>Generated: '+new Date().toLocaleString()+'<br>Rows: <b>'+esc(s.rows??current.rows.length)+'</b>'+Object.entries(s).filter(([k])=>k!=='rows').map(([k,v])=>'<br>'+esc(k)+': <b>'+esc(v)+'</b>').join('')}
  async function generate(){const type=document.getElementById('reportType').value,from=document.getElementById('reportFrom').value,to=document.getElementById('reportTo').value,course=document.getElementById('reportCourse').value;const btn=document.getElementById('generateReport');btn.disabled=true;btn.textContent='Generating…';try{const qs=new URLSearchParams({type,from,to,course});const r=await fetch(API+'/api/admin/reports?'+qs.toString(),{headers:auth()});const d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to generate report');current=d;render();['exportExcel','exportWord','exportPdf'].forEach(id=>document.getElementById(id).disabled=!current.rows.length);await log('generate_report',type,'Generated '+current.title)}catch(e){document.getElementById('reportSummary').textContent=e.message}finally{btn.disabled=false;btn.textContent='Generate Report'}}
  async function log(action,targetId,details){try{await fetch(API+'/api/admin/activity',{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify({action,targetId,details})})}catch{}}
  function matrix(){return [current.columns,...current.rows.map(r=>current.columns.map(c=>r[c]??''))]}
  async function excel(){const ok=await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js',()=>!!window.XLSX);if(!ok){alert('Excel export library could not be loaded.');return}const ws=XLSX.utils.aoa_to_sheet(matrix());ws['!cols']=current.columns.map(c=>({wch:Math.min(40,Math.max(12,String(c).length+3))}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Report');XLSX.writeFile(wb,((current.title||'Report').replace(/[^a-z0-9]+/gi,'_')+'.xlsx'))}
  function word(){const head=current.columns.map(c=>'<th>'+esc(c)+'</th>').join(''),body=current.rows.map(r=>'<tr>'+current.columns.map(c=>'<td>'+esc(r[c])+'</td>').join('')+'</tr>').join('');const html='<!doctype html><html><head><meta charset="utf-8"><title>'+esc(current.title)+'</title><style>body{font-family:Arial,sans-serif;margin:32px}h1{font-size:22px}p{color:#555}table{border-collapse:collapse;width:100%;font-size:10px}th,td{border:1px solid #777;padding:5px;vertical-align:top}th{font-weight:bold}</style></head><body><h1>'+esc(current.title)+'</h1><p>Generated: '+new Date().toLocaleString()+'</p><table><thead><tr>'+head+'</tr></thead><tbody>'+body+'</tbody></table></body></html>';const blob=new Blob(['\ufeff',html],{type:'application/msword'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(current.title||'Report').replace(/[^a-z0-9]+/gi,'_')+'.doc';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function pdf(){const w=window.open('','_blank');if(!w){alert('Please allow pop-ups for PDF/Print export.');return}const head=current.columns.map(c=>'<th>'+esc(c)+'</th>').join(''),body=current.rows.map(r=>'<tr>'+current.columns.map(c=>'<td>'+esc(r[c])+'</td>').join('')+'</tr>').join('');w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+esc(current.title)+'</title><style>@page{size:landscape;margin:10mm}body{font-family:Arial,sans-serif;margin:20px}h1{font-size:20px}p{color:#555}table{border-collapse:collapse;width:100%;font-size:8px}th,td{border:1px solid #777;padding:4px;vertical-align:top}th{font-weight:bold}</style></head><body><h1>'+esc(current.title)+'</h1><p>Generated: '+new Date().toLocaleString()+' | Rows: '+current.rows.length+'</p><table><thead><tr>'+head+'</tr></thead><tbody>'+body+'</tbody></table><script>window.onload=function(){window.print()}<\/script></body></html>');w.document.close()}
  function boot(){addTab();addPane();loadCourses();document.getElementById('generateReport').onclick=generate;document.getElementById('exportExcel').onclick=excel;document.getElementById('exportWord').onclick=word;document.getElementById('exportPdf').onclick=pdf;}
  if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
