const API='http://localhost:5000/api';let lang='en';
const fallbackCourses=[
 {title:{en:'Traffic Management & Vehicle Control',ar:'التحكم بحركات المرور والمركبات'},status:'Available',type:'preview',image:'assets/course-previews/traffic_management_preview.jpg',topics:{en:['Traffic Control','Hand Signals','Site Safety','Vehicle & Pedestrian Management'],ar:['تنظيم حركة المرور','الإشارات اليدوية','سلامة الموقع','إدارة المركبات والمشاة']}},
 {title:{en:'Crowd Management',ar:'إدارة الحشود'},status:'Available',type:'preview',image:'assets/course-previews/crowd_management_preview.jpg',topics:{en:['Crowd Control','Access & Entry Points','Emergency Response','Public Safety'],ar:['السيطرة على الحشود','نقاط الدخول والوصول','الاستجابة للطوارئ','السلامة العامة']}},
 {title:{en:'Fire Safety',ar:'السلامة من الحرائق'},status:'Available',type:'preview',image:'assets/course-previews/fire_safety_preview.jpg',topics:{en:['Fire Prevention','Extinguisher Use','PASS Method','Emergency Procedures'],ar:['الوقاية من الحرائق','استخدام طفايات الحريق','طريقة PASS','إجراءات الطوارئ']}},
 {title:{en:'Vehicle Search & Security Inspection',ar:'تفتيش المركبات والتفتيش الأمني'},status:'Coming Soon',type:'upcoming',image:'assets/course-previews/vehicle_search_preview.jpg',topics:{en:['Vehicle Search Procedures','Concealed-Area Inspection','Prohibited Items','Safe Search Practices'],ar:['إجراءات تفتيش المركبات','فحص المناطق المخفية','المواد المحظورة','ممارسات التفتيش الآمن']}},
 {title:{en:'Person Search & Security Screening',ar:'تفتيش الأشخاص وإجراءات التفتيش الأمني'},status:'Coming Soon',type:'upcoming',image:'assets/course-previews/person_search_preview.jpg',topics:{en:['Person Search Procedures','Metal Detector Screening','X-Ray & Gate Systems','Professional Conduct'],ar:['إجراءات تفتيش الأشخاص','استخدام كاشف المعادن','أجهزة الأشعة السينية والبوابات','السلوك المهني']}},
 {title:{en:'Emergency Response & Evacuation',ar:'الاستجابة للطوارئ والإخلاء'},status:'Coming Soon',type:'upcoming',image:'assets/course-previews/emergency_response_preview.jpg',topics:{en:['Emergency Procedures','Evacuation','Assembly Points','Incident Response'],ar:['إجراءات الطوارئ','الإخلاء','نقاط التجمع','الاستجابة للحوادث']}}
];
const gallery=[
 'assets/images/7f0a702b-3e06-460e-8069-834efb3fdf15.jpg',
 'assets/images/16215897-7e15-44bd-bf5a-7ca85d6856eb.jpg',
 'assets/images/329d370a-3b79-4463-bb91-d360dd88c154(1).jpg',
 'assets/images/6b74190c-2fc3-4870-a467-3cdaed5a17d1.jpg',
 'assets/images/aaefb0e4-4220-45e0-a847-371a84467dab.jpg',
 'assets/images/22f2ca49-4591-4089-82bd-14978dd43415.jpg'
];
function courseText(c){return typeof c.title==='string'?c.title:c.title[lang]}
function imgFallback(){return 'assets/course-previews/course-placeholder.svg'}
function safeImage(src){return src||imgFallback()}
function openCourse(c){const t=courseText(c),topics=(c.topics&&c.topics[lang])||[];document.querySelector('#courseModalBody').innerHTML=`<div class="course-preview"><div class="course-preview-image"><img src="${safeImage(c.image)}" onerror="this.src=imgFallback()" alt="${t}"></div><div><span class="course-status">${c.status||'Available'}</span><h2>${t}</h2><p>${lang==='ar'?'استعراض مختصر للدورة. يتم عرض أجزاء مختارة فقط على الموقع، بينما تبقى المواد التدريبية الكاملة خارج الموقع العام.':'A professional course preview. Only selected highlights are shown publicly; full training materials remain outside the public website.'}</p><h3>${lang==='ar'?'أهم المحاور':'Key Topics'}</h3><ul>${topics.map(x=>`<li>${x}</li>`).join('')}</ul>${c.type==='upcoming'?`<p class="preview-note">${lang==='ar'?'هذه الدورة قادمة وسيتم نشر تفاصيلها عند اكتمال المحتوى.':'This course is coming soon. Details will be published when the training content is ready.'}</p>`:`<p class="preview-note">${lang==='ar'?'الموقع يعرض معاينة فقط — لا يوجد تنزيل مباشر للحقيبة التدريبية.':'Preview only — the original training presentation is not directly downloadable from this website.'}</p>`}</div></div>`;document.getElementById('courseModal').setAttribute('aria-hidden','false')}
function renderCourses(courses=fallbackCourses){document.querySelector('#courseGrid').innerHTML=courses.map(c=>{let t=courseText(c);return `<article class="course-card"><div class="course-card-media"><img src="${safeImage(c.image)}" onerror="this.src=imgFallback()" alt="${t}"><span>${c.status||'Available'}</span></div><div class="course-card-body"><h3>${t}</h3><p>${lang==='ar'?'معاينة مختصرة ومحاور رئيسية من الدورة.':'Selected highlights and key topics from the course.'}</p><button class="btn gold" type="button" data-course='${encodeURIComponent(JSON.stringify(c))}'>${lang==='ar'?'عرض المعاينة':'View Preview'}</button></div></article>`}).join('');document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>openCourse(JSON.parse(decodeURIComponent(b.dataset.course))))}
function renderGallery(){document.querySelector('#galleryGrid').innerHTML=gallery.map(x=>`<img src="${x}" loading="lazy" onerror="this.remove()" alt="Training and professional activity">`).join('')}
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelector('#langBtn').textContent=lang==='en'?'العربية':'English';document.querySelectorAll('[data-en]').forEach(e=>e.textContent=e.dataset[lang]);renderCourses();}
async function loadData(){renderGallery();renderCourses();try{const r=await fetch(`${API}/courses`);if(!r.ok)throw Error();const d=await r.json();if(Array.isArray(d)&&d.length)renderCourses(d);else if(Array.isArray(d.courses)&&d.courses.length)renderCourses(d.courses)}catch(e){}}
document.querySelector('#langBtn').onclick=()=>{lang=lang==='en'?'ar':'en';translate()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).setAttribute('aria-hidden','true'));document.querySelector('#adminBtn').onclick=()=>alert(lang==='ar'?'لوحة الإدارة ستُفعّل عند ربط واجهة الخادم.':'The admin dashboard will be enabled when the production API is connected.');document.querySelector('#adminCourseBtn').onclick=()=>document.querySelector('#adminBtn').click();document.querySelector('#contactForm').onsubmit=e=>{e.preventDefault();document.querySelector('#contactStatus').textContent=lang==='ar'?'تم استلام الرسالة في النموذج. عند نشر الخادم سيتم إرسالها بالبريد.':'Message captured. It will be emailed when the production server is connected.'};loadData();