const API=(window.APP_CONFIG&&window.APP_CONFIG.API_BASE)||'';
let lang='en';

const courses=[
 {slug:'traffic-management-vehicle-control',title:{en:'TRAFFIC MANAGEMENT & VEHICLE CONTROL',ar:'إدارة حركات المرور والتحكم في المركبات بالموقع'},status:'Available',image:'assets/course-previews/traffic_management_preview.jpg',objectives:{en:['Understand the importance of professional site traffic management.','Identify various categories of vehicular and pedestrian traffic.','Master the 6 basic traffic hand signals and whistle codes.','Enforce strict parking rules and deploy parking lot technologies.','Apply traffic calming measures to reduce vehicle speed and accidents.'],ar:['فهم الأهمية البالغة لإدارة وتنظيم حركة المرور في مواقع العمل الحيوية.','تحديد وفصل الفئات المختلفة لحركة المركبات والمشاة لحفظ السلامة.','إتقان الحركات والإشارات الست الأساسية لتوجيه المرور يدوياً وإشارات الصافرة.','تطبيق قواعد المواقف الصارمة وتوظيف تقنيات إدارة المواقف الحديثة.','تطبيق تدابير تهدئة حركة المرور الهندسية لخفض السرعات والحد من الحوادث.']}},
 {slug:'crowd-management-event-security',title:{en:'CROWD MANAGEMENT & EVENT SECURITY',ar:'إدارة الحشود وتأمين الفعاليات والمناسبات الكبرى'},status:'Available',image:'assets/course-previews/crowd_management_preview.jpg',objectives:{en:['Understand the basic concepts of crowd dynamics and group psychology.','Analyze different categories of crowds and expect their behaviors.','Apply 8 scientific countermeasures to control hostile and unruly crowds.','Deploy basic riot and crowd control formations in special events.','Implement strict access control and screening policies in Gulf environments.'],ar:['فهم المفاهيم الأساسية لديناميكيات الحشود وعلم نفس الجماهير.','تحليل الفئات المختلفة للحشود وتوقع مسارات سلوكياتها بدقة.','تطبيق 8 تدابير مضادة علمية للسيطرة على الحشود المشاغبة والعدائية.','نشر وتشكيل قوات مكافحة الشغب والسيطرة على الحشود في الفعاليات.','تطبيق سياسات صارمة لتنظيم الدخول والتفتيش تلائم بيئة الخليج العربي.']}},
 {slug:'fire-safety-emergency-response',title:{en:'FIRE SAFETY & EMERGENCY RESPONSE',ar:'السلامة من الحرائق وتدابير الاستجابة للطوارئ'},status:'Available',image:'assets/course-previews/fire_safety_preview.jpg',objectives:{en:['Master the core physics and chemistry of fire tetrahedron dynamics.','Identify fire classifications and select portable agents per NFPA 10.','Demonstrate proper response and validation of fire alarm systems.','Apply tactical countermeasures including RACE, arson prevention, and security.','Manage mass evacuations and incident command structures per NFPA 101.'],ar:['إتقان المفاهيم الأساسية لكيمياء الحريق وديناميكيات رباعي الأوجه.','تصنيف أنواع الحرائق واختيار وسائط الإطفاء المناسبة بموجب NFPA 10.','تطبيق الاستجابة الصحيحة وتأكيد تنبيهات لوحات الكشف والإنذار.','تنفيذ تدابير الوقاية مثل RACE، ومكافحة الافتعال المتعمد، وتأمين المنشأة.','قيادة عمليات الإخلاء الجماعي وإدارة الحوادث بموجب معايير NFPA 101.']}}
];

const gallery=['assets/images/7f0a702b-3e06-460e-8069-834efb3fdf15.jpg','assets/images/16215897-7e15-44bd-bf5a-7ca85d6856eb.jpg','assets/images/329d370a-3b79-4463-bb91-d360dd88c154(1).jpg','assets/images/6b74190c-2fc3-4870-a467-3cdaed5a17d1.jpg','assets/images/aaefb0e4-4220-45e0-a847-371a84467dab.jpg','assets/images/22f2ca49-4591-4089-82bd-14978dd43415.jpg'];
const imgFallback='assets/course-previews/course-placeholder.svg';
const t=c=>c.title[lang];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

function renderGallery(){document.querySelector('#galleryGrid').innerHTML=gallery.map(x=>`<img src="${x}" loading="lazy" onerror="this.remove()" alt="Training and professional activity">`).join('')}
function statCard(icon,en,ar,value){return `<div class="metric"><span class="metric-icon">${icon}</span><div><strong>${value}</strong><span>${lang==='ar'?ar:en}</span></div></div>`}
function metricsHtml(m){const empty='—';m=m||{};return `<div class="course-metrics">${statCard('◉','Views','المشاهدات',m.views??empty)}${statCard('↗','Course Entries','عدد مرات الدخول',m.entries??empty)}${statCard('👍','Positive Ratings','التقييمات الإيجابية',m.positiveRatings!=null?`${m.positiveRatings}%`:empty)}${statCard('★','Average Rating','متوسط التقييم',m.ratingCount?`${Number(m.averageRating||0).toFixed(1)}/5`:empty)}</div>`}
async function getStats(slug){if(!API)return null;try{const r=await fetch(`${API}/api/course-stats/${encodeURIComponent(slug)}`,{credentials:'omit'});if(!r.ok)throw Error();return await r.json()}catch(e){return null}}
async function recordEntry(slug){if(!API)return;try{await fetch(`${API}/api/course-stats/${encodeURIComponent(slug)}/entry`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'entry'})})}catch(e){}}
async function rateCourse(slug,rating){if(!API)return {ok:false,offline:true};try{const r=await fetch(`${API}/api/course-stats/${encodeURIComponent(slug)}/rating`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating})});return {ok:r.ok,data:r.ok?await r.json():null}}catch(e){return {ok:false}}}

async function openCourse(c){await recordEntry(c.slug);const stats=await getStats(c.slug);const objectives=c.objectives[lang];document.querySelector('#courseModalBody').innerHTML=`<div class="course-detail"><div class="course-detail-media"><img src="${c.image}" onerror="this.src='${imgFallback}'" alt="${esc(t(c))}"></div><div class="course-detail-content"><span class="course-status">${esc(lang==='ar'?'متاحة':'Available')}</span><h2>${esc(t(c))}</h2><div class="objective-title">${lang==='ar'?'أهداف الدورة والمخرجات التعليمية':'Course Objectives & Learning Outcomes'}</div><ul class="objectives">${objectives.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="preview-note">${lang==='ar'?'هذه الصفحة تعرض معاينة مختارة فقط. المواد التدريبية الكاملة غير متاحة للتنزيل العام.':'This page provides a selected preview only. Full training materials are not publicly downloadable.'}</p></div></div><div id="courseMetrics">${metricsHtml(stats)}</div><div class="rating-box"><div><strong>${lang==='ar'?'قيّم الدورة':'Rate this course'}</strong><span>${lang==='ar'?'تقييمك يساعد على تطوير المحتوى التدريبي.':'Your rating helps improve the training content.'}</span></div><div class="rating-buttons">${[1,2,3,4,5].map(n=>`<button type="button" data-rate="${n}" aria-label="${n} stars">★</button>`).join('')}</div><div id="ratingStatus" class="status"></div></div>`;document.getElementById('courseModal').setAttribute('aria-hidden','false');document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=async()=>{const n=Number(b.dataset.rate);const res=await rateCourse(c.slug,n);const st=document.getElementById('ratingStatus');if(res.ok){st.textContent=lang==='ar'?'تم تسجيل تقييمك. شكراً لك.':'Your rating has been recorded. Thank you.';document.getElementById('courseMetrics').innerHTML=metricsHtml(res.data)}else st.textContent=lang==='ar'?'نظام التقييم غير متصل حالياً.':'The rating system is not connected yet.'})}
function renderCourses(){document.querySelector('#courseGrid').innerHTML=courses.map(c=>`<article class="course-card"><div class="course-card-media"><img src="${c.image}" onerror="this.src='${imgFallback}'" alt="${esc(t(c))}"><span>${lang==='ar'?'متاحة':'Available'}</span></div><div class="course-card-body"><h3>${esc(t(c))}</h3><p>${lang==='ar'?'أهداف الدورة ومحاور مختارة مع إحصائيات حية عند الاتصال بالنظام.':'Course objectives, selected highlights and live metrics when the system is connected.'}</p><button class="btn gold" type="button" data-course="${c.slug}">${lang==='ar'?'عرض الدورة':'View Course'}</button></div></article>`).join('');document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>openCourse(courses.find(c=>c.slug===b.dataset.course)))}
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelector('#langBtn').textContent=lang==='en'?'العربية':'English';document.querySelectorAll('[data-en]').forEach(e=>e.textContent=e.dataset[lang]);renderCourses()}
async function loadData(){renderGallery();renderCourses();if(API){for(const c of courses){const s=await getStats(c.slug);const el=document.querySelector(`[data-course="${c.slug}"]`);if(s&&el){const card=el.closest('.course-card');card.querySelector('.course-card-body').insertAdjacentHTML('beforeend',metricsHtml(s))}}}}
document.querySelector('#langBtn').onclick=()=>{lang=lang==='en'?'ar':'en';translate()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).setAttribute('aria-hidden','true'));document.querySelector('#adminBtn').onclick=()=>alert(lang==='ar'?'لوحة الإدارة ستُفعّل عند ربط واجهة الخادم.':'The admin dashboard will be enabled when the production API is connected.');document.querySelector('#adminCourseBtn').onclick=()=>document.querySelector('#adminBtn').click();document.querySelector('#contactForm').onsubmit=e=>{e.preventDefault();document.querySelector('#contactStatus').textContent=lang==='ar'?'تم استلام الرسالة في النموذج. عند نشر الخادم سيتم إرسالها بالبريد.':'Message captured. It will be emailed when the production server is connected.'};loadData();