(function(){
  const API=(window.APP_CONFIG&&window.APP_CONFIG.API_BASE)||'https://security-instructor.onrender.com';
  const VID_KEY='siVisitorId',SESSION_KEY='siVisitorSession',CONSENT_KEY='siAnalyticsConsent';
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const visitorId=()=>{let v=localStorage.getItem(VID_KEY);if(!v){v='VIS-'+cryptoRandom();localStorage.setItem(VID_KEY,v)}return v};
  const cryptoRandom=()=>{try{return crypto.randomUUID().replace(/-/g,'').slice(0,20)}catch{return Math.random().toString(36).slice(2)+Date.now().toString(36)}};
  const sessionId=()=>{let v=sessionStorage.getItem(SESSION_KEY);if(!v){v='SES-'+cryptoRandom();sessionStorage.setItem(SESSION_KEY,v)}return v};
  const source=()=>{const q=new URLSearchParams(location.search),u=(q.get('utm_source')||q.get('source')||'').toLowerCase();if(u)return u;const r=(document.referrer||'').toLowerCase();return r.includes('linkedin')?'linkedin':r.includes('instagram')?'instagram':r.includes('tiktok')?'tiktok':r.includes('facebook')?'facebook':r.includes('youtube')?'youtube':'direct'};
  async function post(path,body){try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Request failed');return d}catch(e){return {error:e.message}}}
  function loadCss(){if(document.querySelector('link[data-si-security-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='security-visitor.css?v=20260916';l.dataset.siSecurityCss='1';document.head.appendChild(l)}
  function shield(){if(document.querySelector('.si-screen-shield'))return;const d=document.createElement('div');d.className='si-screen-shield';d.innerHTML='<div><strong>Protected Training Content / محتوى تدريبي محمي</strong><span>This screen is protected. Please return to the assessment or challenge to continue.<br>هذه الشاشة محمية. عد إلى التقييم أو التحدي للمتابعة.</span></div>';document.body.appendChild(d);return d}
  function protect(){loadCss();document.body.classList.add('si-protected');const mark=document.createElement('div');mark.textContent='SECURITY INSTRUCTOR • PROTECTED';mark.style.cssText='position:fixed;right:12px;bottom:10px;z-index:2147482000;font:700 10px Arial;color:rgba(200,169,107,.65);pointer-events:none;letter-spacing:.08em';document.body.appendChild(mark);const s=shield();document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('copy',e=>e.preventDefault());document.addEventListener('cut',e=>e.preventDefault());document.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('keydown',e=>{const k=String(e.key||'').toLowerCase();if(k==='printscreen'||(e.ctrlKey&&(k==='p'||k==='s'||k==='u'))||(e.ctrlKey&&e.shiftKey&&(k==='i'||k==='j'||k==='c'))){e.preventDefault();e.stopPropagation();s.style.display='flex'}});document.addEventListener('visibilitychange',()=>{s.style.display=document.hidden?'flex':'none'});window.addEventListener('blur',()=>{s.style.display='flex'});window.addEventListener('focus',()=>{setTimeout(()=>{if(!document.hidden)s.style.display='none'},250)});}
  function privacy(){loadCss();if(localStorage.getItem(CONSENT_KEY))return Promise.resolve(true);const d=document.createElement('div');d.className='si-privacy';d.innerHTML='<div class="si-privacy-text"><div class="si-privacy-title">Privacy & Visitor Analytics / الخصوصية وتحليلات الزوار</div><div>We use a limited visitor ID and visit/assessment activity to operate the challenge, assessment and certificate service and understand traffic sources. No account is required. / نستخدم معرّف زائر محدودًا ونشاط الزيارة والتقييم لتشغيل التحدي والتقييم والشهادة وفهم مصادر الزيارات، ولا يلزم إنشاء حساب.</div></div><div class="si-privacy-actions"><button class="si-accept">Allow / موافق</button><button class="si-deny">Essential Only / الأساسي فقط</button></div>';document.body.appendChild(d);return new Promise(resolve=>{d.querySelector('.si-accept').onclick=async()=>{localStorage.setItem(CONSENT_KEY,'yes');d.remove();await post('/api/visitor/consent',{visitorId:visitorId(),analyticsConsent:true});resolve(true)};d.querySelector('.si-deny').onclick=()=>{localStorage.setItem(CONSENT_KEY,'essential');d.remove();resolve(false)}})}
  async function recordSession(consent){if(!consent)return;const key='siSessionRecorded:'+sessionId();if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');await post('/api/visitor/session',{visitorId:visitorId(),sessionId:sessionId(),source:source(),landingPath:location.pathname,referrer:document.referrer,analyticsConsent:true})}
  function certPrompt(data){loadCss();const wrap=document.createElement('div');wrap.className='si-cert';wrap.style.display='flex';wrap.innerHTML='<div class="si-cert-card"><div class="si-cert-eyebrow">SECURITY INSTRUCTOR</div><h1>Certificate of Achievement</h1><h2>شهادة إتمام</h2><div class="si-cert-form" style="display:block"><input id="siRecipientName" maxlength="160" placeholder="Full Name / الاسم الكامل" autocomplete="name"><div class="si-cert-note">Enter the name exactly as you want it printed on the certificate. / اكتب الاسم كما تريد ظهوره في الشهادة.</div><div class="si-cert-actions"><button class="si-primary" id="siIssue">Issue Certificate / إصدار الشهادة</button></div></div><div id="siCertError" class="si-cert-note"></div></div>';document.body.appendChild(wrap);wrap.querySelector('#siIssue').onclick=async()=>{const name=wrap.querySelector('#siRecipientName').value.trim();if(name.length<2){wrap.querySelector('#siCertError').textContent='Please enter your full name / يرجى إدخال الاسم الكامل';return}const r=await post('/api/visitor/certificate',{visitorId:visitorId(),attemptId:data.attemptId,recipientName:name});if(r.error){wrap.querySelector('#siCertError').textContent=r.error+' / تعذر إصدار الشهادة';return}location.href='certificate.html?id='+encodeURIComponent(r.certificateId)}}
  async function startAttempt(type,courseSlug){const r=await post('/api/visitor/attempt/start',{visitorId:visitorId(),sessionId:sessionId(),type,courseSlug,source:source()});if(r.error)return r;return r}
  async function completeAttempt(attemptId,score){return post('/api/visitor/attempt/complete',{visitorId:visitorId(),attemptId,score})}
  function setupChallenge(){if(typeof window.startChallenge!=='function'||window.__siChallengeWrapped)return;window.__siChallengeWrapped=true;window.startChallenge=async function(bank){const gate=await startAttempt('challenge','');if(gate.error){alert(gate.error+' / لا يمكن بدء محاولة جديدة');return}let index=0,score=0;let pick=[...bank].sort(()=>Math.random()-.5);const byLevel=l=>pick.filter(q=>q.level===l);pick=[...byLevel('Intermediate').slice(0,4),...byLevel('Good').slice(0,4),...byLevel('Very Good').slice(0,2)].sort(()=>Math.random()-.5);if(pick.length<10)pick=[...bank].sort(()=>Math.random()-.5).slice(0,10);pick=pick.map(q=>{const order=[0,1,2,3];for(let j=3;j>0;j--){const k=Math.floor(Math.random()*(j+1));[order[j],order[k]]=[order[k],order[j]]}return Object.assign({},q,{options:{en:order.map(i=>q.options.en[i]),ar:order.map(i=>q.options.ar[i])},correctAnswer:order.indexOf(q.correctAnswer)})});const app=document.querySelector('#challengeApp');function render(){const q=pick[index];app.innerHTML='<div class="challenge-card"><div class="challenge-top"><span>Question '+(index+1)+' of 10 / السؤال '+(index+1)+' من 10</span><span>'+(q.level==='Intermediate'?'🟢 متوسط':q.level==='Good'?'🔵 جيد':'🟣 جيد جدًا')+'</span></div><h3>'+esc(q.question.en)+'</h3><h4 dir="rtl">'+esc(q.question.ar)+'</h4><div class="challenge-options">'+q.options.map((o,i)=>'<button data-answer="'+i+'"><span dir="ltr">'+esc(o.en)+'</span><span dir="rtl">'+esc(o.ar)+'</span></button>').join('')+'</div><div class="challenge-progress"><i style="width:'+(index/10*100)+'%"></i></div></div>';app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const chosen=+b.dataset.answer;if(chosen===q.correctAnswer)score++;index++;if(index<10)render();else finish()})}async function finish(){const result=await completeAttempt(gate.attemptId,score);const pass=score>=7;app.innerHTML='<div class="challenge-result"><div class="result-score">'+score+'<small>/10</small></div><h3>Your Security Knowledge Level / مستواك في المعرفة الأمنية</h3><strong>'+ (score>=8?'Very Good / جيد جدًا':score>=7?'Good / جيد':'Intermediate / متوسط')+'</strong><p>'+ (pass?'Congratulations — you reached the certificate passing score of 7/10. / تهانينا — حققت درجة النجاح المطلوبة للشهادة وهي 7 من 10.':'Keep learning and try again once if this was your first attempt. / استمر في التعلم ويمكنك إعادة المحاولة مرة واحدة إذا كانت هذه محاولتك الأولى.')+'</p>'+(pass?'<button id="siChallengeCert" class="btn gold">Issue Certificate / إصدار الشهادة</button>':'<button id="challengeAgain" class="btn gold">Try Again / حاول مرة أخرى</button>')+'</div>';if(pass){app.querySelector('#siChallengeCert').onclick=()=>certPrompt({attemptId:gate.attemptId})}else{app.querySelector('#challengeAgain').onclick=()=>window.startChallenge(bank)};if(result.error)console.warn(result.error)}render()}}
  function setup(){if(location.pathname.endsWith('index.html')||location.pathname==='/'||location.pathname.endsWith('/security-instructor/')){privacy().then(recordSession).then(()=>{protect();setTimeout(setupChallenge,800);setInterval(setupChallenge,1200)})}}
  window.SIVisitorSecurity={visitorId,sessionId,source,startAttempt,completeAttempt,certPrompt};
  loadCss();setup();
})();
