const express=require('express');
const mongoose=require('mongoose');
const crypto=require('crypto');
const clean=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';
const verifyAdmin=req=>{try{const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return false;const t=h.slice(7),p=t.split('.');const secret=process.env.ADMIN_SESSION_SECRET||'',email=(process.env.ADMIN_EMAIL||'Abdallah-Shalaby1@outlook.com').trim().toLowerCase();if(!secret||p.length!==2)return false;const sig=crypto.createHmac('sha256',secret).update(p[0]).digest('base64url');const a=Buffer.from(p[1]),b=Buffer.from(sig);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return false;const x=JSON.parse(Buffer.from(p[0],'base64url').toString('utf8'));return !!x.exp&&x.exp>Date.now()&&String(x.email||'').toLowerCase()===email}catch{return false}};
const courses={
 'traffic-management-vehicle-control':{code:'CRS-TRAFFIC-001',name:'TRAFFIC MANAGEMENT & VEHICLE CONTROL'},
 'crowd-management-event-security':{code:'CRS-CROWD-001',name:'CROWD MANAGEMENT & EVENT SECURITY'},
 'fire-safety-emergency-response':{code:'CRS-FIRE-001',name:'FIRE SAFETY & EMERGENCY RESPONSE'},
 'vehicle-search-security-inspection':{code:'CRS-VEHICLE-001',name:'VEHICLE SEARCH & SECURITY INSPECTION'},
 'person-search-security-screening':{code:'CRS-PERSON-001',name:'PERSON SEARCH & SECURITY SCREENING'}
};
const dateOf=x=>x?.registeredAt||x?.createdAt||x?.submittedAt||x?.completedAt||x?.date||null;
const inRange=(x,from,to)=>{const d=dateOf(x);if(!d)return !from&&!to;const t=new Date(d).getTime();if(Number.isNaN(t))return false;if(from&&t<new Date(from+'T00:00:00').getTime())return false;if(to&&t>new Date(to+'T23:59:59.999').getTime())return false;return true};
const flatten=(o,p='',r={})=>{if(o==null)return r;if(o instanceof Date){r[p]=o.toISOString();return r}if(Array.isArray(o)){r[p]=o.map(v=>typeof v==='object'?JSON.stringify(v):String(v)).join(' | ');return r}if(typeof o==='object'){for(const [k,v] of Object.entries(o)){if(k==='_id'||k==='__v')continue;const q=p?p+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v)&&!(v instanceof Date))flatten(v,q,r);else r[q]=v}return r}r[p]=o;return r};
const safe=rows=>rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>{const x=k.toLowerCase();return !x.includes('password')&&!x.includes('token')&&!x.includes('secret')})));
async function collections(names){const db=mongoose.connection.db;if(!db)return null;const all=(await db.listCollections({}, {nameOnly:true}).toArray()).map(x=>x.name);return names.find(n=>all.includes(n))||null}
function register(app){
 app.get('/api/site-content',async(req,res)=>{try{const c=mongoose.connection.collection('sitecontents');const defaults=[['homeEyebrow','PROFESSIONAL TRAINING • PRACTICAL SKILLS • SAFER WORKPLACES','تدريب احترافي • مهارات عملية • بيئات عمل أكثر أمانًا'],['homeName','Abdallah Abdelaziz Shalaby','عبدالله عبدالعزيز شلبي'],['homeRole','Training Support Executive | Fire Safety Trainer | LMS Specialist','مسؤول دعم التدريب | مدرب السلامة من الحرائق | أخصائي نظام إدارة التعلّم'],['homeIntro','Building safer people, safer workplaces and stronger security performance through practical training, professional standards and real-world readiness.','نبني أفرادًا أكثر أمانًا، وبيئات عمل أكثر أمانًا، وأداءً أمنيًا أكثر كفاءة من خلال التدريب العملي والمعايير المهنية والجاهزية الواقعية.'],['homeQuote','“Invest in your skills. Strengthen your readiness. Build a safer workplace.”','“استثمر في مهاراتك، وعزّز جاهزيتك، وابنِ بيئة عمل أكثر أمانًا.”'],['aboutTitle','About Me','نبذة عني'],['aboutLead','Abdallah Abdelaziz Shalaby is a certified Security Trainer and LMS Specialist with 17+ years of professional experience across the GCC, including Saudi Arabia, the United Arab Emirates and Qatar.','عبدالله عبدالعزيز شلبي مدرب أمني وأخصائي نظام إدارة التعلّم، يتمتع بخبرة مهنية تتجاوز 17 عامًا في دول مجلس التعاون الخليجي، تشمل المملكة العربية السعودية والإمارات العربية المتحدة ودولة قطر.'],['experienceTitle','Professional Experience','الخبرة المهنية'],['trainingTitle','Training Areas','مجالات التدريب'],['galleryTitle','Training & Professional Gallery','معرض التدريب والأعمال'],['coursesTitle','Courses & Training','الدورات التدريبية'],['projectsTitle','Projects & Ideas','المشاريع والأفكار']];for(const x of defaults)await c.updateOne({key:x[0]},{$setOnInsert:{key:x[0],en:x[1],ar:x[2],createdAt:new Date(),updatedAt:new Date()}},{upsert:true});res.json(await c.find({},{projection:{_id:0,key:1,en:1,ar:1,updatedAt:1}}).sort({key:1}).toArray())}catch(e){console.error('site content public error',e);res.status(500).json({message:'Unable to load site content'})}});
 const content=async(req,res)=>{if(!verifyAdmin(req))return res.status(401).json({message:'Admin authentication required'});try{const c=mongoose.connection.collection('sitecontents');if(req.method==='GET')return res.json(await c.find({},{projection:{_id:0,key:1,en:1,ar:1,updatedAt:1}}).sort({key:1}).toArray());const b=req.body||{},key=clean(b.key,80);if(!key)return res.status(400).json({message:'Content key is required'});const set={key,en:clean(b.en,2000),ar:clean(b.ar,2000),updatedAt:new Date()};await c.updateOne({key},{$set:set},{upsert:true});res.json({ok:true,...set})}catch(e){console.error('site content admin error',e);res.status(500).json({message:'Unable to save site content'})}};
 app.get('/api/admin/site-content',content);app.patch('/api/admin/site-content',content);
 const activity=async(req,res)=>{if(!verifyAdmin(req))return res.status(401).json({message:'Admin authentication required'});try{const c=mongoose.connection.collection('adminactivity');if(req.method==='GET')return res.json(await c.find({}).sort({createdAt:-1}).limit(200).toArray());const b=req.body||{},d={action:clean(b.action,80),targetId:clean(b.targetId,160),details:clean(b.details,500),createdAt:new Date()};if(!d.action)return res.status(400).json({message:'Activity action is required'});await c.insertOne(d);res.status(201).json({...d,id:String(d._id)})}catch(e){res.status(500).json({message:'Unable to save activity'})}};
 app.get('/api/admin/activity',activity);app.post('/api/admin/activity',activity);
 const report=async(req,res)=>{if(!verifyAdmin(req))return res.status(401).json({message:'Admin authentication required'});try{const type=clean(req.query.type,30)||'courses',from=clean(req.query.from,20),to=clean(req.query.to,20),course=clean(req.query.course,80);let title,rows=[];
 if(type==='trainees'){const ts=await mongoose.connection.collection('trainees').find({}).sort({createdAt:-1}).limit(10000).toArray(),es=await mongoose.connection.collection('enrollments').find({}).sort({registeredAt:-1}).limit(20000).toArray();rows=ts.filter(x=>inRange(x,from,to)).map(t=>{const own=es.filter(e=>e.traineeId===t.traineeId);return {'Trainee ID':t.traineeId,'Arabic First Name':t.arabicFirstName,'Arabic Middle Name':t.arabicMiddleName,'Arabic Last Name':t.arabicLastName,'English First Name':t.englishFirstName,'English Middle Name':t.englishMiddleName,'English Last Name':t.englishLastName,'ID Type':t.idType,'ID Number':t.idNumber,'Mobile':t.mobile,'Email':t.email,'Registration Date':t.createdAt?.toISOString?.()||'','Enrollment Count':own.length,'Enrollment IDs':own.map(e=>e.enrollmentId).join(' | '),'Courses':own.map(e=>e.courseNameEn).join(' | '),'Course Statuses':own.map(e=>e.status).join(' | '),'Registration Types':own.map(e=>e.registrationType).join(' | '),'Companies':own.map(e=>e.companyName||'').filter(Boolean).join(' | '),'Course Registration Dates':own.map(e=>e.registeredAt?.toISOString?.()||'').join(' | ')}});title='Trainee Master Report';
 }else if(type==='courses'){const es=await mongoose.connection.collection('enrollments').find({}).sort({registeredAt:-1}).limit(10000).toArray(),F=await mongoose.connection.collection('coursefeedbacks').find({}).sort({createdAt:-1}).toArray();rows=Object.entries(courses).filter(([s])=>!course||s===course).map(([slug,c])=>{const list=es.filter(e=>e.courseId===c.code||e.courseSlug===slug).filter(e=>inRange(e,from,to)),fb=F.filter(x=>x.slug===slug&&inRange(x,from,to));const starts=list.map(e=>e.registeredAt).filter(Boolean).sort((a,b)=>a-b),ends=list.map(e=>e.registeredAt).filter(Boolean).sort((a,b)=>b-a);return {'Week':starts[0]?starts[0].toISOString().slice(0,10):'','Course Code':c.code,'Batch Number':'','Course Name':c.name,'Hours Used':'','Date Start':starts[0]?starts[0].toISOString().slice(0,10):'','Date End':ends[0]?ends[0].toISOString().slice(0,10):'','Stream (B2I / B2C )':'','Instructor':'','Project / Sponsor / Client':'','Enrolled All Streams':list.length,'B2B Client Revenue':'','B2C Learners':'','B2C Learner Attended Revenue':'','B2I Learners':'','B2I Learner Attended Revenue':'','Status (Cancelled / Completed)':[...new Set(list.map(e=>e.status))].join(' / '),'Feedback Completed (Yes / No)':fb.length?'Yes':'No','Number of Negative Feedbacks':'','Pass':'','Fail':'','Absent':''}});title='Training Courses Report';
 }else if(type==='feedback'){const F=await mongoose.connection.collection('coursefeedbacks').find({}).sort({createdAt:-1}).limit(10000).toArray();rows=F.filter(x=>inRange(x,from,to)&&(!course||x.slug===course)).map(x=>({'Course':courses[x.slug]?.name||x.slug,'Course Slug':x.slug,'Feedback':x.note,'Date':x.createdAt?.toISOString?.()||''}));title='Feedback Report';
 }else if(type==='challenge'){const C=await mongoose.connection.collection('challengeattempts').find({}).sort({startedAt:-1}).limit(10000).toArray();rows=C.filter(x=>inRange(x,from,to)).map(x=>({'Attempt ID':x.attemptId,'Started At':x.startedAt?.toISOString?.()||'','Completed At':x.completedAt?.toISOString?.()||'','Score':x.score??'','Max Score':10,'Status':x.completedAt?'Completed':'Started'}));title='Challenge Results Report';
 }else if(type==='assessments'||type==='complaints'){const name=await collections(type==='assessments'?['assessmentresults','assessment_results','assessmentattempts','assessment_attempts','testresults','test_results']:['traineecomplaints','trainee_complaints','complaints','complaintmessages']);if(name){const d=await mongoose.connection.collection(name).find({}).sort({createdAt:-1}).limit(5000).toArray();rows=safe(d.filter(x=>inRange(x,from,to)).map(flatten));}title=type==='assessments'?'Assessment Results Report':'Trainee Complaints Report';
 }else return res.status(400).json({message:'Unsupported report type'});
 res.json({title,columns:[...new Set(rows.flatMap(r=>Object.keys(r)))].length?[...new Set(rows.flatMap(r=>Object.keys(r)))]:['Status'],rows,summary:{rows:rows.length},generatedAt:new Date().toISOString()})}catch(e){console.error('runtime report error',e);res.status(500).json({message:'Unable to generate report'})}};
 app.get('/api/admin/reports',report);
}
if(!express.application.__si_admin_runtime_listen){express.application.__si_admin_runtime_listen=true;const original=express.application.listen;express.application.listen=function(...args){try{register(this)}catch(e){console.error('admin runtime route registration error',e)}return original.apply(this,args)}}
