const express=require('express');
const mongoose=require('mongoose');
const install=(method,path,handler)=>{const key='__si_reports_'+method+'_'+path.replace(/[^a-z0-9]/gi,'_');if(express.application[key])return;express.application[key]=true;const original=express.application[method];express.application[method]=function(route,...handlers){if(route===path)original.call(this,route,handler);return original.call(this,route,...handlers)}};
const clean=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';
const ctrlAuth=async req=>{try{const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return false;const r=await fetch('http://127.0.0.1:'+(process.env.PORT||10000)+'/api/admin/me',{headers:{Authorization:h}});return r.ok}catch{return false}};
const courses={'traffic-management-vehicle-control':{code:'CRS-TRAFFIC-001',name:'TRAFFIC MANAGEMENT & VEHICLE CONTROL'},'crowd-management-event-security':{code:'CRS-CROWD-001',name:'CROWD MANAGEMENT & EVENT SECURITY'},'fire-safety-emergency-response':{code:'CRS-FIRE-001',name:'FIRE SAFETY & EMERGENCY RESPONSE'},'vehicle-search-security-inspection':{code:'CRS-VEHICLE-001',name:'VEHICLE SEARCH & SECURITY INSPECTION'},'person-search-security-screening':{code:'CRS-PERSON-001',name:'PERSON SEARCH & SECURITY SCREENING'}};
const byCode=Object.fromEntries(Object.entries(courses).map(([slug,c])=>[c.code,{...c,slug}]));
const dateOf=x=>x?.registeredAt||x?.submittedAt||x?.assessedAt||x?.startedAt||x?.createdAt||x?.completedAt||x?.date||null;
const inRange=(x,from,to)=>{const d=dateOf(x);if(!d)return !from&&!to;const t=new Date(d).getTime();if(Number.isNaN(t))return false;if(from&&t<new Date(from+'T00:00:00').getTime())return false;if(to&&t>new Date(to+'T23:59:59.999').getTime())return false;return true};
const safeValue=v=>v instanceof Date?v.toISOString():v==null?'':v;
const normalizeCourse=x=>{const slug=x?.courseSlug||x?.slug||x?.course?.slug||'';const code=x?.courseId||x?.courseCode||x?.course?.code||'';const c=byCode[code]||courses[slug];return c?{...c}:{slug,code,name:x?.courseName||x?.courseNameEn||x?.course||''}};
const matchesCourse=(x,course)=>{if(!course)return true;const c=normalizeCourse(x);return course===c.slug||course===c.code||course===x?.courseId||course===x?.courseSlug};
const flatten=(obj,prefix='',out={})=>{if(obj==null)return out;if(obj instanceof Date){out[prefix]=obj.toISOString();return out}if(Array.isArray(obj)){out[prefix]=obj.map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(' | ');return out}if(typeof obj==='object'){for(const [k,v] of Object.entries(obj)){if(k==='_id'||k==='__v')continue;const key=prefix?prefix+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v)&&!(v instanceof Date))flatten(v,key,out);else out[key]=safeValue(v)}return out}out[prefix]=obj;return out};
const safeRows=rows=>rows.map(r=>{const o={};for(const [k,v] of Object.entries(r)){const lk=k.toLowerCase();if(lk.includes('password')||lk.includes('token')||lk.includes('secret'))continue;o[k]=safeValue(v)}return o});
const candidates={assessments:['assessmentresults','assessment_results','assessmentattempts','assessment_attempts','testresults','test_results'],complaints:['traineecomplaints','trainee_complaints','complaints','complaintmessages']};
async function existingCollection(names){const db=mongoose.connection.db;if(!db)return null;const namesNow=(await db.listCollections({}, {nameOnly:true}).toArray()).map(x=>x.name);return names.find(n=>namesNow.includes(n))||null}
const first=(o,keys)=>{for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&String(v)!=='')return v}return ''};
const fmtDate=v=>v?new Date(v).toISOString().slice(0,10):'';
const reportHandler=async(req,res)=>{if(!(await ctrlAuth(req)))return res.status(401).json({message:'Admin authentication required'});try{const type=clean(req.query?.type,30)||'courses',from=clean(req.query?.from,20),to=clean(req.query?.to,20),course=clean(req.query?.course,80),status=clean(req.query?.status,40),registrationType=clean(req.query?.registrationType,30);let result;
if(type==='courses'){const E=mongoose.connection.collection('enrollments'),F=mongoose.connection.collection('coursefeedbacks');const allE=await E.find({}).sort({registeredAt:-1}).limit(20000).toArray(),feedback=await F.find({}).sort({createdAt:-1}).limit(20000).toArray();const es=allE.filter(x=>inRange(x,from,to)&&matchesCourse(x,course)&&(!status||x.status===status)&&(!registrationType||x.registrationType===registrationType));const rows=Object.entries(courses).filter(([slug])=>!course||slug===course).map(([slug,c])=>{const list=es.filter(x=>x.courseId===c.code||x.courseSlug===slug),dates=list.map(x=>x.registeredAt).filter(Boolean).sort((a,b)=>new Date(a)-new Date(b)),fb=feedback.filter(x=>x.slug===slug&&inRange(x,from,to)),counts={pending:0,confirmed:0,active:0,completed:0,cancelled:0};list.forEach(x=>{if(counts[x.status]!==undefined)counts[x.status]++});return {'Course Code':c.code,'Course':c.name,'Registrations':list.length,'Pending':counts.pending,'Confirmed':counts.confirmed,'Active':counts.active,'Completed':counts.completed,'Cancelled':counts.cancelled,'Feedback':fb.length,'First Registration':fmtDate(dates[0]),'Last Registration':fmtDate(dates[dates.length-1])}});result={title:'Training Courses Report',columns:['Course Code','Course','Registrations','Pending','Confirmed','Active','Completed','Cancelled','Feedback','First Registration','Last Registration'],rows,summary:{rows:rows.length,totalRegistrations:es.length,totalFeedback:feedback.filter(x=>inRange(x,from,to)&&(!course||x.slug===course)).length}};
}else if(type==='trainees'){const T=mongoose.connection.collection('trainees'),E=mongoose.connection.collection('enrollments');const [ts,allE]=await Promise.all([T.find({}).sort({createdAt:-1}).limit(10000).toArray(),E.find({}).sort({registeredAt:-1}).limit(30000).toArray()]);const es=allE.filter(x=>inRange(x,from,to)&&matchesCourse(x,course)&&(!status||x.status===status)&&(!registrationType||x.registrationType===registrationType));const rows=ts.map(t=>{const own=es.filter(e=>e.traineeId===t.traineeId),allOwn=allE.filter(e=>e.traineeId===t.traineeId),last=own.map(e=>e.registeredAt).filter(Boolean).sort((a,b)=>new Date(b)-new Date(a))[0];return {'Trainee ID':t.traineeId,'Name':[t.englishFirstName,t.englishMiddleName,t.englishLastName].filter(Boolean).join(' '),'ID Number':t.idNumber,'Mobile':t.mobile,'Email':t.email,'Courses':own.length,'Active':own.filter(e=>e.status==='active').length,'Completed':own.filter(e=>e.status==='completed').length,'Cancelled':own.filter(e=>e.status==='cancelled').length,'Last Registration':fmtDate(last),'Course List':[...new Set(own.map(e=>e.courseNameEn).filter(Boolean))].join(' | '),'All-Time Enrollments':allOwn.length}}).filter(r=>!from&&!to&&!course&&!status&&!registrationType||r.Courses>0);result={title:'Trainee Master Report',columns:['Trainee ID','Name','ID Number','Mobile','Email','Courses','Active','Completed','Cancelled','Last Registration','Course List','All-Time Enrollments'],rows,summary:{rows:rows.length}};
}else if(type==='feedback'){const F=mongoose.connection.collection('coursefeedbacks');const rows=(await F.find({}).sort({createdAt:-1}).limit(20000).toArray()).filter(x=>inRange(x,from,to)&&(!course||x.slug===course)).map(x=>{const c=courses[x.slug]||{};return {'Course Code':c.code||'','Course':c.name||x.slug||'','Feedback':x.note||'','Date':fmtDate(x.createdAt)}});result={title:'Feedback Report',columns:['Course Code','Course','Feedback','Date'],rows,summary:{rows:rows.length}};
}else if(type==='challenge'){const C=mongoose.connection.collection('challengeattempts');const rows=(await C.find({}).sort({startedAt:-1}).limit(20000).toArray()).filter(x=>inRange(x,from,to)).map(x=>{const score=x.score;return {'Attempt ID':x.attemptId,'Started':fmtDate(x.startedAt),'Completed':fmtDate(x.completedAt),'Score':score??'','Result':score==null?'In Progress':Number(score)>=5?'Pass':'Fail','Status':x.completedAt?'Completed':'Started'}});result={title:'Challenge Results Report',columns:['Attempt ID','Started','Completed','Score','Result','Status'],rows,summary:{rows:rows.length,completed:rows.filter(x=>x.Status==='Completed').length}};
}else if(type==='assessments'||type==='complaints'){const name=await existingCollection(candidates[type]);
let docs=name?await mongoose.connection.collection(name).find({}).sort({createdAt:-1}).limit(10000).toArray():[];
let sourceCollection=name||'';
if(type==='assessments'&&!name){
  const enrollmentDocs=await mongoose.connection.collection('enrollments').find({score:{$ne:null}}).sort({registeredAt:-1}).limit(10000).toArray();
  docs=enrollmentDocs.map(x=>({...x,assessmentScore:x.score,assessmentResult:x.assessmentResult||x.result||''}));
  sourceCollection='enrollments.score';
}
const filtered=docs.filter(x=>inRange(x,from,to)&&matchesCourse(x,course)&&(!status||String(first(x,['status','result','outcome','assessmentResult'])).toLowerCase()===status.toLowerCase()));if(type==='assessments'){const rows=Array.from(new Map(filtered.map(x=>{const c=normalizeCourse(x);const key=[first(x,['traineeId','traineeID','studentId']),c.code||c.name,first(x,['attempt','attemptNumber','attemptNo'])||'1'].join('|');return [key,x]})).values()).map(x=>{const c=normalizeCourse(x);return {'Assessment ID':first(x,['assessmentId','attemptId','resultId','_id','enrollmentId']),'Trainee ID':first(x,['traineeId','traineeID','studentId']),'Course Code':c.code,'Course':c.name,'Attempt':first(x,['attempt','attemptNumber','attemptNo'])||'1','Score':first(x,['assessmentScore','score','percentage','mark']),'Result':first(x,['result','outcome','assessmentResult','status']),'Date':fmtDate(dateOf(x)),'Retake':first(x,['retake','isRetake'])}}));result={title:'Assessment Results Report',columns:['Assessment ID','Trainee ID','Course Code','Course','Attempt','Score','Result','Date','Retake'],rows,summary:{rows:rows.length,sourceCollection:sourceCollection||'Not available'}};}else{const rows=filtered.map(x=>({'Complaint ID':first(x,['complaintId','id','_id']),'Trainee ID':first(x,['traineeId','traineeID','studentId']),'Course':normalizeCourse(x).name||first(x,['course','courseName','courseNameEn']),'Category':first(x,['category','type','subject']),'Priority':first(x,['priority','severity']),'Status':first(x,['status','state']),'Submitted':fmtDate(first(x,['submittedAt','createdAt','date'])),'Resolution':fmtDate(first(x,['resolvedAt','resolutionDate','closedAt'])),'Summary':first(x,['summary','message','description','complaint'])}));result={title:'Trainee Complaints Report',columns:['Complaint ID','Trainee ID','Course','Category','Priority','Status','Submitted','Resolution','Summary'],rows,summary:{rows:rows.length,sourceCollection:name||'Not available'}};}}
else return res.status(400).json({message:'Unsupported report type'});res.json({...result,generatedAt:new Date().toISOString(),filters:{type,from,to,course,status,registrationType}})}catch(e){console.error('report generation error',e);res.status(500).json({message:'Unable to generate report'})}};
install('get','/api/admin/reports',reportHandler);
if(!express.application.__si_reports_listen){
  express.application.__si_reports_listen=true;
  const originalListen=express.application.listen;
  express.application.listen=function(...args){
    try{this.get('/api/admin/reports',reportHandler)}catch(e){console.error('reports route registration error',e)}
    return originalListen.apply(this,args)
  }
}
require('./operations-routes.js');
