const express=require('express');
const mongoose=require('mongoose');
const install=(method,path,handler)=>{const key='__si_reports_'+method+'_'+path.replace(/[^a-z0-9]/gi,'_');if(express.application[key])return;express.application[key]=true;const original=express.application[method];express.application[method]=function(route,...handlers){if(route===path)original.call(this,route,handler);return original.call(this,route,...handlers)}};
const clean=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';
const ctrlAuth=async req=>{try{const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return false;const r=await fetch('http://127.0.0.1:'+(process.env.PORT||10000)+'/api/admin/me',{headers:{Authorization:h}});return r.ok}catch{return false}};
const courses={'traffic-management-vehicle-control':{code:'CRS-TRAFFIC-001',name:'TRAFFIC MANAGEMENT & VEHICLE CONTROL'},'crowd-management-event-security':{code:'CRS-CROWD-001',name:'CROWD MANAGEMENT & EVENT SECURITY'},'fire-safety-emergency-response':{code:'CRS-FIRE-001',name:'FIRE SAFETY & EMERGENCY RESPONSE'},'vehicle-search-security-inspection':{code:'CRS-VEHICLE-001',name:'VEHICLE SEARCH & SECURITY INSPECTION'},'person-search-security-screening':{code:'CRS-PERSON-001',name:'PERSON SEARCH & SECURITY SCREENING'}};
const dateOf=x=>x?.registeredAt||x?.createdAt||x?.submittedAt||x?.completedAt||x?.date||null;
const inRange=(x,from,to)=>{const d=dateOf(x);if(!d)return !from&&!to;const t=new Date(d).getTime();if(Number.isNaN(t))return false;if(from&&t<new Date(from+'T00:00:00').getTime())return false;if(to&&t>new Date(to+'T23:59:59.999').getTime())return false;return true};
const flatten=(obj,prefix='',out={})=>{if(obj==null)return out;if(obj instanceof Date){out[prefix]=obj.toISOString();return out}if(Array.isArray(obj)){out[prefix]=obj.map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(' | ');return out}if(typeof obj==='object'){for(const [k,v] of Object.entries(obj)){if(k==='_id'||k==='__v')continue;const key=prefix?prefix+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v)&&!(v instanceof Date))flatten(v,key,out);else out[key]=v}return out}out[prefix]=obj;return out};
const safeRows=rows=>rows.map(r=>{const o={};for(const [k,v] of Object.entries(r)){const lk=k.toLowerCase();if(lk.includes('password')||lk.includes('token')||lk.includes('secret'))continue;o[k]=v instanceof Date?v.toISOString():v}return o});
const candidates={assessments:['assessmentresults','assessment_results','assessmentattempts','assessment_attempts','testresults','test_results'],complaints:['traineecomplaints','trainee_complaints','complaints','complaintmessages']};
async function existingCollection(names){const db=mongoose.connection.db;if(!db)return null;const namesNow=(await db.listCollections({}, {nameOnly:true}).toArray()).map(x=>x.name);return names.find(n=>namesNow.includes(n))||null}
async function getGeneric(type,from,to){const name=await existingCollection(candidates[type]||[]);if(!name)return {columns:['Status'],rows:[],summary:{rows:0,note:'No matching database collection is currently present.'}};const docs=await mongoose.connection.collection(name).find({}).sort({createdAt:-1}).limit(5000).toArray();const rows=safeRows(docs.filter(x=>inRange(x,from,to)).map(flatten));const columns=[...new Set(rows.flatMap(r=>Object.keys(r)))];return {columns:columns.length?columns:['Status'],rows,summary:{rows:rows.length,sourceCollection:name}}}
const reportHandler=async(req,res)=>{if(!(await ctrlAuth(req)))return res.status(401).json({message:'Admin authentication required'});try{const type=clean(req.query?.type,30)||'courses',from=clean(req.query?.from,20),to=clean(req.query?.to,20),course=clean(req.query?.course,80),status=clean(req.query?.status,40);let result;
if(type==='courses'){const E=mongoose.connection.collection('enrollments'),S=mongoose.connection.collection('coursestats'),F=mongoose.connection.collection('coursefeedbacks');const chosen=courses[course]?.code||course||'';const es=(await E.find({}).sort({registeredAt:-1}).limit(10000).toArray()).filter(x=>inRange(x,from,to)&&(!course||x.courseId===chosen||x.courseSlug===course)&&(!status||x.status===status));const feedback=await F.find({}).sort({createdAt:-1}).toArray();const stats=await S.find({}).toArray();const rows=Object.entries(courses).filter(([slug])=>!course||slug===course).map(([slug,c])=>{const list=es.filter(x=>x.courseId===c.code||x.courseSlug===slug),fb=feedback.filter(x=>x.slug===slug&&inRange(x,from,to));const dates=list.map(x=>x.registeredAt).filter(Boolean).sort((a,b)=>new Date(a)-new Date(b));const endDates=list.map(x=>x.registeredAt).filter(Boolean).sort((a,b)=>new Date(b)-new Date(a));return {'Week':dates[0]?new Date(dates[0]).toISOString().slice(0,10):'','Course Code':c.code,'Batch Number':'','Course Name':c.name,'Hours Used':'','Date Start':dates[0]?new Date(dates[0]).toISOString().slice(0,10):'','Date End':endDates[0]?new Date(endDates[0]).toISOString().slice(0,10):'','Stream (B2I / B2C )':'','Instructor':'','Project / Sponsor / Client':'','Enrolled All Streams':list.length,'B2B Client Revenue':'','B2C Learners':'','B2C Learner Attended Revenue':'','B2I Learners':'','B2I Learner Attended Revenue':'','Status (Cancelled / Completed)':list.length?[...new Set(list.map(x=>x.status))].join(' / '):'','Feedback Completed (Yes / No)':fb.length?'Yes':'No','Number of Negative Feedbacks':'','Pass':'','Fail':'','Absent':''}});result={title:'Training Courses Report',columns:Object.keys(rows[0]||{'Course Name':''}),rows,summary:{rows:rows.length,enrollments:es.length,feedbackEntries:feedback.filter(x=>(!course||x.slug===course)&&inRange(x,from,to)).length,courseFilter:course?courses[course]?.name||course:'All Courses'}};
}else if(type==='trainees'){const T=mongoose.connection.collection('trainees'),E=mongoose.connection.collection('enrollments');const ts=(await T.find({}).sort({createdAt:-1}).limit(10000).toArray()).filter(x=>inRange(x,from,to));const es=await E.find({}).sort({registeredAt:-1}).limit(20000).toArray();const rows=ts.map(t=>{const own=es.filter(e=>e.traineeId===t.traineeId);return {'Trainee ID':t.traineeId,'Arabic First Name':t.arabicFirstName,'Arabic Middle Name':t.arabicMiddleName,'Arabic Last Name':t.arabicLastName,'English First Name':t.englishFirstName,'English Middle Name':t.englishMiddleName,'English Last Name':t.englishLastName,'ID Type':t.idType,'ID Number':t.idNumber,'Mobile':t.mobile,'Email':t.email,'Registration Date':t.createdAt?new Date(t.createdAt).toISOString():'','Enrollment Count':own.length,'Enrollment IDs':own.map(e=>e.enrollmentId).join(' | '),'Courses':own.map(e=>e.courseNameEn).join(' | '),'Course Statuses':own.map(e=>e.status).join(' | '),'Registration Types':own.map(e=>e.registrationType).join(' | '),'Companies':own.map(e=>e.companyName||'').filter(Boolean).join(' | '),'Course Registration Dates':own.map(e=>e.registeredAt?new Date(e.registeredAt).toISOString():'').join(' | ')}});result={title:'Trainee Master Report',columns:Object.keys(rows[0]||{'Trainee ID':''}),rows,summary:{rows:rows.length}};
}else if(type==='feedback'){const F=mongoose.connection.collection('coursefeedbacks'),rows=(await F.find({}).sort({createdAt:-1}).limit(10000).toArray()).filter(x=>inRange(x,from,to)&&(!course||x.slug===course)).map(x=>({'Course':courses[x.slug]?.name||x.slug,'Course Slug':x.slug,'Feedback':x.note,'Date':x.createdAt?new Date(x.createdAt).toISOString():''}));result={title:'Feedback Report',columns:['Course','Course Slug','Feedback','Date'],rows,summary:{rows:rows.length}};
}else if(type==='challenge'){const C=mongoose.connection.collection('challengeattempts'),rows=(await C.find({}).sort({startedAt:-1}).limit(10000).toArray()).filter(x=>inRange(x,from,to)).map(x=>({'Attempt ID':x.attemptId,'Started At':x.startedAt?new Date(x.startedAt).toISOString():'','Completed At':x.completedAt?new Date(x.completedAt).toISOString():'','Score':x.score??'','Max Score':10,'Status':x.completedAt?'Completed':'Started'}));result={title:'Challenge Results Report',columns:['Attempt ID','Started At','Completed At','Score','Max Score','Status'],rows,summary:{rows:rows.length}};
}else if(type==='assessments'||type==='complaints'){result=await getGeneric(type,from,to);result.title=type==='assessments'?'Assessment Results Report':'Trainee Complaints Report';
}else return res.status(400).json({message:'Unsupported report type'});
res.json({...result,generatedAt:new Date().toISOString(),filters:{type,from,to,course,status}});
}catch(e){console.error('report generation error',e);res.status(500).json({message:'Unable to generate report'})}};
install('get','/api/admin/reports',reportHandler);
